#!/bin/bash
#### date command: macOS

#### Common variables
bin_dir=$HOME/bin
prayer_dir=$HOME/Sites/theologic.us/content/posts/prayer
templates=$bin_dir/30/templates
once_template=$templates/once.md

# Clear current weeks
weeks=$bin_dir/weeks
true > $weeks

echo "Last entry for $prayer_dir: "
echo "$(ls -1 $prayer_dir | grep md | tail -n1)"

# Set the prompt for the select command
echo "Setting up prayers within your Prayer Journal"
PS3="Select a date or "q" to quit: "

# Give me the next 30 days to choose from
for i in {0..30}; do
  echo "$(date -j -v +"$i"d +%F)" >> $weeks
done

listofdates=$(cat $weeks)

# Show a menu and ask for input.
select selectdate in $listofdates; do
    if [ -n "$selectdate" ]; then
        echo ${selectdate}
    fi
    break
done

echo "Publishing prayer_dir for Prayer Journal starting on "$selectdate"!"

read -p "Are you sure? " -n 1 -r
echo
if [[ $REPLY =~ ^[Yy]$ ]]
then
  for j in {0..30}; do
  export date_prayers=`date -j -v+"$j"d -f "%Y-%m-%d" "$selectdate" +%F`
  export day_prayers=`date -j -v+"$j"d -f "%Y-%m-%d" "$selectdate" +'%A, %-e %B %Y'`
  export dow_prayers=`date -j -v+"$j"d -f "%Y-%m-%d" "$selectdate" +"%F-%a"`
  export once_time=T05:00:00-05:00
  export css="prayers"
  envsubst < $once_template > "$prayer_dir"/"$dow_prayers"-prayer.md
done
fi
