#!/bin/bash
#### date command: macOS

#### Post and date specific variables
Tag="Titus"
tag="titus"
title="Gospel NT: "
url_cat="gospel-nt"
Category="Gospel NT"
time="T06:00:00-05:00"
css="prayers"

subject="$title$Tag"
subject_dir=$(date -j +%Y)
url_sub="$url_cat-$tag"
Series="$subject"

#### Common variables
bin_dir=$HOME/bin
posts_dir=$HOME/Sites/theologic.us/content/posts/$subject_dir
# posts_dir=$HOME/Temp/$subject_dir

# mkdir working directory if there is none
mkdir -p "$posts_dir"

# Clear current weeks
weeks=$bin_dir/weeks
true > $weeks

echo "Last entry for $subject: "
echo "$(ls -1 $posts_dir | grep md | grep $tag | tail -n1)"

lastdate=$(head $posts_dir/`ls -1 $posts_dir | grep md | grep $tag | tail -n1` | grep publishDate)
echo $lastdate

# Set the prompt for the select command
echo "Setting up posts for $subject: "
PS3="Select a date or "q" to quit: "

# Give me the next 60 days to choose from
for i in {0..60}; do
  echo "$(date -j -v +"$i"d +%F)" >> $weeks
done

listofdates=$(cat $weeks)

# Show a menu and ask for input.
select selectdate in $listofdates; do
    if [ -n "$selectdate" ]; then
        echo ${selectdate}
    fi
    break
done

echo "Publishing "$subject" starting on "$selectdate"!"

read -p "Are you sure? " -n 1 -r
echo
if [[ $REPLY =~ ^[Yy]$ ]]
then
	for j in {0..30}; do
  postdate=$(date -j -v +"$j"d -f "%Y-%m-%d" "$selectdate" +%F)
  cat << EOF > "$posts_dir"/"$url_sub""$j".md
---
title: "$title"
author: Joseph Louthan
publishDate: $postdate$time
categories:
  - $Category
tags:
  - "$Tag"
series:
  - "$Series"
tocopen: true
css: "$css"
draft: true
---
## The Introduction

<div style="page-break-after: always;"></div>

## The Text

<div style="page-break-after: always;"></div>

## The Meditation


## The Gospel


## The Discussion

\`\`\`text
1. 
\`\`\`

\`\`\`text
2. 
\`\`\`

\`\`\`text
3. 
\`\`\`

\`\`\`text
4. 
\`\`\`

## The Prayer

<div style='font-variant: small-caps;'>

</div>

\`\`\`text

\`\`\`


EOF
	done
fi
