#!/bin/bash
#### date command: macOS

#### Post and date specific variables
Tag="Romans"
tag="romans"
title="Study: "
url_cat="study"
Category="Study"

time="T06:00:00-06:00"
css="prayers"

subject="$title$Tag"
subject_dir=2022
url_sub="$url_cat-$tag"
Series="$subject"

#### Common variables
bin_dir=$HOME/bin
posts_dir=$HOME/Sites/theologic.us/content/posts/$subject_dir
# posts_dir=$HOME/Temp/$subject_dir

# mkdir working directory if there is none
mkdir -p "$posts_dir"

# Clear current weeks
weeks=$bin_dir/weeks
true > $weeks

echo "Last entry for $subject: "
echo "$(ls -1 $posts_dir | grep md | grep $tag | tail -n1)"

lastdate=$(head $posts_dir/`ls -1 $posts_dir | grep md | grep $tag | tail -n1` | grep publishDate)
echo $lastdate

# Set the prompt for the select command
echo "Setting up posts for $subject: "
PS3="Select a date or "q" to quit: "

# Give me the next 60 days to choose from
for i in {0..60}; do
  echo "$(date -j -v +"$i"d +%F)" >> $weeks
done

listofdates=$(cat $weeks)

# Show a menu and ask for input.
select selectdate in $listofdates; do
    if [ -n "$selectdate" ]; then
        echo ${selectdate}
    fi
    break
done

echo "Publishing "$subject" starting on "$selectdate"!"

read -p "Are you sure? " -n 1 -r
echo
if [[ $REPLY =~ ^[Yy]$ ]]
then
	for j in {0..30}; do
  postdate=$(date -j -v +"$j"d -f "%Y-%m-%d" "$selectdate" +%F)
  cat << EOF > "$posts_dir"/"$url_sub""$j".md
---
title: "$title"
author: Joseph Louthan
publishDate: $postdate$time
categories:
  - $Category
tags:
  - "$Tag"
series:
  - "$Series"
tocopen: true
css: "$css"
draft: true
---
## The Introduction

<div style="page-break-after: always;"></div>

## The Text

## The Support

<div style="page-break-after: always;"></div>

\`\`\`text
Where do you see God in the text? What does the text say about God?
\`\`\`

## Our God

<div style="page-break-after: always;"></div>

## The Gospel

<div style="page-break-after: always;"></div>

## Our Response

## The Discussion

\`\`\`text
1. 
\`\`\`

\`\`\`text
2. 
\`\`\`

\`\`\`text
3. 
\`\`\`

\`\`\`text
4. 
\`\`\`

## The Prayer

<div style='font-variant: small-caps;'>

</div>

\`\`\`text

\`\`\`

## The Media

Today's episode at [The Study](http://study.theologic.us/podcast/)

\[[Apple](https://podcasts.apple.com/us/podcast/the-study/id1557102127)\]\[[Spotify](https://open.spotify.com/show/0Xs5qsNvWePyRqcmtOTPkR)\]\[[YouTube](http://youtube.theologic.us)\]\[[Twitch](http://twitch.theologic.us)\]\[[Twitter](https://twitter.com/theologic_us)\]\[[Facebook](https://www.facebook.com/groups/462231051477464)\]\[[Afreeca](https://bj.afreecatv.com/theologicus)\]\[[Discord](http://discord.theologic.us)\]

## Resources

[<img src="https://images-na.ssl-images-amazon.com/images/I/91DXb+atXsL.jpg" align="left" width="100" style="padding-right: 10px" />Christian Standard Bible](https://amzn.to/3FbGqbM).  
Holmon Publishing. 2020.  
&nbsp;

___

[<img src="https://images-na.ssl-images-amazon.com/images/I/41nNWgurO3L._SX394_BO1,204,203,200_.jpg" align="left" width="100" style="padding-right: 10px" />ESV Study Bible](https://amzn.to/3FbGs38).  
Crossway. 2016.

&nbsp;

___

[<img src="https://images-na.ssl-images-amazon.com/images/I/41mjq2lbVJL._SX330_BO1,204,203,200_.jpg" align="left" width="100" style="padding-right: 10px" />Calvin's Commentaries](https://www.olivetree.com/store/product.php?productid=17517).  
by John Calvin.  
Baker. 2009.

&nbsp;

___

[<img src="https://images-na.ssl-images-amazon.com/images/I/51utvezkAcL._SX323_BO1,204,203,200_.jpg" align="left" width="100" style="padding-right: 10px" />No Condemnation in Christ Jesus: As Unfolded in the Eighth Chapter of the Epistle to the Romans](https://amzn.to/3zDFiMZ).  
by Octavius Winslow.  
Banner of Trust. 1991.  
&nbsp;  

___

<p style="clear:both;">

[<img src="https://images-na.ssl-images-amazon.com/images/I/51enHREddML._SX343_BO1,204,203,200_.jpg" align="left" width="100" style="padding-right: 10px" />Romans: An Expositional Commentary](https://amzn.to/3GaYTGJ).  
by R.C. Sproul.  
Reformation Trust Publishing. 2019.  

&nbsp;

___

<p style="clear:both;">

[<img src="https://images-na.ssl-images-amazon.com/images/I/510tS0bc3jL._SX336_BO1,204,203,200_.jpg" align="left" width="100" style="padding-right: 10px" />The Letter to the Romans (New International Commentary on the New Testament (NICNT))](https://amzn.to/3tcauBO).  
by Douglas Moo.  
First Edition.  
Eerdmans. 1996.  

___

<p style="clear:both;">

[<img src="https://images-na.ssl-images-amazon.com/images/I/51JRo7sUdGL._SY291_BO1,204,203,200_QL40_FMwebp_.jpg" align="left" width="100" style="padding-right: 10px" />New Testament Commentary: Romans: Chapters 1-16](https://amzn.to/3zHvu4D).  
by William Hendriksen.  
Baker. 1992.  

&nbsp;

___

<p style="clear:both;">

[<img src="https://books.google.com/books/content?id=nn1EAAAACAAJ&printsec=frontcover&img=1&zoom=1&imgtk=AFLRE72sbduWDe-FDdpJWpEdxA39XGAk1Gn13nRRTn19x0PuOx37CIrB_n2nhpSVq7yoiqH1iW6sP9z5Yug16kxtKECC1uxXNf6EawIr8vLirT5K_YS7G7ji9NtjXaKf_FVMtPRbBX4B" align="left" width="100" style="padding-right: 10px" />Romans](https://amzn.to/3zFAIxv).  
by William S. Plumer.  
Kregel. 1993.  

&nbsp;

___

<p style="clear:both;">

[<img src="https://images-na.ssl-images-amazon.com/images/I/41Oh-dWTyCL._SX318_BO1,204,203,200_.jpg" align="left" width="100" style="padding-right: 10px" />Romans: An Exegetical and Theological Exposition of Holy Scripture (The New American Commentary)](https://amzn.to/33hjElg).  
by Robert Mounce.  
Holmon Reference. 1995.  
&nbsp;

___

<p style="clear:both;">

[<img src="https://images-na.ssl-images-amazon.com/images/I/51XmpThqFeS._SY291_BO1,204,203,200_QL40_FMwebp_.jpg" align="left" width="100" style="padding-right: 10px" />Romans (Ancient Christian Commentary on Scripture, NT Volume 6)](https://amzn.to/3HLaNra).  
Edited by Gerald L. Bray.  
IVP Academic. 2005.  

&nbsp;

___

<p style="clear:both;">

[<img src="https://images-na.ssl-images-amazon.com/images/I/41yNgHWAm0L._SY291_BO1,204,203,200_QL40_FMwebp_.jpg" align="left" width="100" style="padding-right: 10px" />Commentary on Romans](https://amzn.to/3r13Tat).  
by Martin Luther.  
Kregel. 2003.  

&nbsp;

___

EOF
  done
fi