#! /bin/bash
# date command: macOS

prayers=$HOME/Sites/prayers/
genprayers=$prayers/gen_prayers
date_prayers=`date -j +%F`

echo "============================================="
echo "Generating new prayers and commit gen-prayers"
cd $bin
$genprayers
read -p "Commit descript: " desc
git add $genprayers && \
git add -u &&\
git commit -m "$desc" && \
git push origin master

echo "==========================="
echo "Now committing new prayers"
cd $theologicus && \
git add $prayers/* && \
git add -u &&\
git commit -m "$desc" && \
git push origin master
