#!/bin/sh
# Displays a list of files in current directory and prompt for which
# file to edit

current_dir=$HOME/bin
ls -la $current_dir | grep '^\S*x\S*' | awk '{print $9}' | grep -v '\.' | grep -v createtheo > $current_dir/bin_list

# Set the prompt for the select command
PS3="Type a number or 'q' to quit: "

# Create a list of files to display
script_list=$(cat $current_dir/bin_list)

# Show a menu and ask for input. If the user entered a valid choice,
# then invoke the editor on that file
select script in $script_list; do
    if [ -n "$script" ]; then
		$script
    fi
    break
done
