#! /bin/bash

site=$HOME/Projects/ansible-scripts

echo "======================"
echo "Checking master branch"
cd $site
git pull origin master

echo "========================="
echo "Proceeding with deploy..."
cd $site
read -p "Commit descript: " desc
git add . &&\
git add -u &&\
git commit -m "$desc" &&\
git push
