#! /bin/bash
# date command: MACOS

current_dir=$HOME/bin/
content_dir=$HOME/Sites/theologic.us/content/posts
dir_prayers=$content_dir/prayers
base_am_prayers=am_prayers
base_noon_prayers=noon_prayers
base_pm_prayers=pm_prayers
first_day=1
last_day=31
# loop: print out 1-30
for ((i=$first_day;i<=$last_day;i++)); 
do 
   date_prayers=`date -j -v+"$i"d +%F`
   day_prayers=`date -j -v+"$i"d +'%A, %-e %B %Y'`
   am_time=T06:00:00-06:00
   noon_time=T12:00:00-06:00
   pm_time=T20:00:00-06:00
   cat << EOF > "$dir_prayers"/"$date_prayers"-"$base_am_prayers".md
---
title: 'Morning Prayers for $day_prayers'
author: Joseph Louthan
type: post
publishDate: $date_prayers$am_time
url: /$base_am_prayers/$date_prayers-$base_am_prayers/
categories:
 - Prayers
tags:
 - 'Prayers'
draft: true
---



---

# Pray to preach the gospel

> **2 Timothy 4:1-5 (ESV) I charge you in the presence of God and of Christ Jesus, who is to judge the living and the dead, and by his appearing and his kingdom: preach the word; be ready in season and out of season; reprove, rebuke, and exhort, with complete patience and teaching. For the time is coming when people will not endure sound teaching, but having itching ears they will accumulate for themselves teachers to suit their own passions, and will turn away from listening to the truth and wander off into myths. As for you, always be sober-minded, endure suffering, do the work of an evangelist, fulfill your ministry.**

---

# For Sarah

Melissa

Steph

Erin

Faith

Melody

Natasha

Jamie

---

# Give thanks

---

# For healing

My Lord,

I pray for that you would heal:

Heal Faithie. My Lord above, heal my sweet cousin. Comfort her and speak peace. Lay your hand upon her head and continuously give her peace forever. Take care of her and give her body and mind and nervous system healing always. Hold her together with your hands and heart.

Heal Sean. Vertigo double focus. Lord heal his mind and body. Give him rest and peace. Lord show him the love you have for him.

Heal Gerry. Be with Jan and all of the Melenkas in this time.

Heal Randy (Jordan Mayfield's dad) - possible hospice

Heal Kathleen (Leah's mom)

---

# Daily

On marriage: **Sarah, my love** 

On true friendship: **For my Jonathan** 

On sanctification: **Lord, help me to gentle, patient, and tender like you** 

On holiness: **2 Timothy 2:21 Therefore, if anyone cleanses himself from what is dishonorable, he will be a vessel for honorable use, set apart as holy, useful to the master of the house, ready for every good work.**

Lord, as you draw me closer, please Lord please stop making everything about me. Please beat it out of me that i somehow think i am God’s gift to women. I still see lust on my heart and I still want to look at every woman not my wife.  World is telling me lies. But you have gave me eyes for my wife over anyone else. One day you will remove the foolish, prideful, lustful instincts and thoughts in thinking every woman is after me. I am a fool and a sinner. Every day I will repent. Discipline your son as you see fit but make me more like your Son.  Do not let your Spirit depart from me. Amen.

On prophesying: **Lord, let me preach your gospel, die, and then be forgotten** 

On pastoring: **Lord, I cared not where or how I lived, or what hardships I went through, so I could but gain souls to Christ. —Henry Martyn** 

On teaching: **“He who would be a good teacher must be gentle and leave some means to draw those who come to him, that he may win them.” —John Calvin**

On evangelizing: **As soon as the line snaps: “In your ministry, you will gain two and lose one. Will that be good enough for you.”**

On glory of God: **“On Christ’s glory I would fix all my thoughts and desires, and the more I see of the glory of Christ, the more the painted beauties of this world will wither in my eyes and I will be more and more crucified to this world. It will become to me like something dead and putrid, impossible for me to enjoy.” ― John Owen, The Glory of Christ**

On his provision: **Lord, anything you give will be good enough for me.**

---

# Next steps

My God,

I am so uncertain. What are my next steps? Direct me, Holy Spirit.

But I will praise you for the triple blessings of being with the staff. Bless them and keep them always.

Amen

---

# For those who do not know You

My Lord above,

Call on me. I will be obedient. Tell me with whom shall I share your good news: you are Jesus and you have saved his people from their sins. If they believe and trust in you, they will live.

**Logan**

**Chuck's sons, Zachary & Samuel**

**Aussie's folks: Brad & Gay, 3 brothers**

**Emily's mom, Cheri**

**Yusef and Nichole** 

**Elijah & Ivy, Amber & Kara, Griffen, Gabe, Emma, Lacey, Grace, Lucy**

**Natalie, Jackson, Kingston** 

**Reed & Sandy** 

**Johnny & Jamie, Kolton, Korbin** 

**Jeanny** 

**Jodi & Ryan, Piper, Rylee** 

**Jennifer & John; Brandon; Phillip & Keri, Haley; Meagan & fam ; Pedigo & Deb** 

**Melissa & Micah, Noah, Levi, Judah** 

**James** 

**Jason, Molly** 

**Chelsea**

**Jansen & Mandy** 

**Sean & Sunny** 

**Evan** 

**Shannon & Michael, Elle**

**Patrick (Dave’s Son)**

**Coleman & Wendy, Olivia, Bella, Ian**

**Carl**

**Mark & Nicole, Gabrielle** 

**Mark & Robin** 

**James & Hubs**

**Louis** 

**Greg & wife** 

**Liz** 

**Eileen & Hubs, fam** 

**Ray** 

**Randall** 

**Cynthia** 

**Joe P** 

**George** 

**Margo & kids**

**Vinny & wife**

**Ali**

**Homie**

**Wayne & Nicole Barber** 

**Eric Robinson** 

**Jonathan & Jenn Williams** 

**Evan & Kaylee, Everett, Baby**

---

# Friends

**Sarah & Josiah**

**Jared & Lacey, Marin, Elisabeth**

**Leslie**

**Andrew & Jordyn, Will, Alice, Elliot, Annie** 

**Alix & Braden** 

**Aaron & Natasha, Audrey**

**Holly & Jake, Jonah, Ellis, Finley**

**Jason & Michelle, Hazel, Charlette, Evelyn** 

**Landon & Jules, Eli, Sophia & Olivia**

**California**
- Moray
- Sarah and Mike Neustadt
- Layne and Jackie Marshall
- Evie
- Kristie 
- John and Gina
- Jen and Diddy 
EOF
   cat << EOF > "$dir_prayers"/"$date_prayers"-"$base_noon_prayers".md
---
title: 'Noon Prayers for $day_prayers'
author: Joseph Louthan
type: post
publishDate: $date_prayers$noon_time
url: /$base_noon_prayers/$date_prayers-$base_noon_prayers/
categories:
 - Prayers
tags:
 - 'Prayers'
draft: true
---

<pre>
<div style="font-variant: small-caps;">
</div>

</pre>

---

**Isaiah 61 (ESV)**

**The Spirit of the Lord GOD is upon me,**

**because the LORD has anointed me**

**to bring good news to the poor;**

**he has sent me to bind up the brokenhearted,**

**to proclaim liberty to the captives,**

**and the opening of the prison to those who are bound;**

**to proclaim the year of the LORD'S favor,**

**and the day of vengeance of our God;**

**to comfort all who mourn;**

**to grant to those who mourn in Zion—**

**to give them a beautiful headdress instead of ashes,**

**the oil of gladness instead of mourning,**

**the garment of praise instead of a faint spirit;**

**that they may be called oaks of righteousness,**

**the planting of the LORD, that he may be glorified.**

**They shall build up the ancient ruins;**

**they shall raise up the former devastations;**

**they shall repair the ruined cities,**

**the devastations of many generations.**

**Strangers shall stand and tend your flocks;**

**foreigners shall be your plowmen and vinedressers;**

**but you shall be called the priests of the LORD;**

**they shall speak of you as the ministers of our God;**

**you shall eat the wealth of the nations,**

**and in their glory you shall boast.**

**Instead of your shame there shall be a double portion;**

**instead of dishonor they shall rejoice in their lot;**

**therefore in their land they shall possess a double portion;**

**they shall have everlasting joy.**

**For I the LORD love justice;**

**I hate robbery and wrong;**

**I will faithfully give them their recompense,**

**and I will make an everlasting covenant with them.**

**Their offspring shall be known among the nations,**

**and their descendants in the midst of the peoples;**

**all who see them shall acknowledge them,**

**that they are an offspring the LORD has blessed.**

**I will greatly rejoice in the LORD;**

**my soul shall exult in my God,**

**for he has clothed me with the garments of salvation;**

**he has covered me with the robe of righteousness,**

**as a bridegroom decks himself like a priest with a beautiful headdress,**

**and as a bride adorns herself with her jewels.**

**For as the earth brings forth its sprouts,**

**and as a garden causes what is sown in it to sprout up,**

**so the Lord GOD will cause righteousness and praise**

**to sprout up before all the nations.**

---

# Family

**Sarah, Yusef, Elijah, Ivy, Ava**

**Marmie & Jason, Molly**

---

# Norman

> **Matthew 3:12 (CSB) His winnowing shovel is in his hand, and he will clear his threshing floor and gather his wheat into the barn. But the chaff he will burn with fire that never goes out.”**

Andrew & Kate McCracken

Megan & JD Reeves

Larissa Mainers

Kim Burns

Taylor Smith

Lori Stanton

John Baldwin

Faith and Chris Allen

Misti & Cole Brackin

Seth & Lauren Hartman

Craig Conaway

Dustin & Shyla Stokes

Roy & Amy Griffin

Liz & Trey Davidson

Aimee & James Coker

**Sean & Sunny** 

**Evan** 

---

# Antioch Norman

- Tatenda
- Desiree
- Manasha
- Ashley
- Abby
- Noah
- Rin
- Laurel
- Courtney
- Faith
- Max
- Brad
- Elijah
- Crystal
- Pam
- Leah
- Marisha
- Stacy
- Carol
- Sam
- Shandra
- Isaac
- Susan
- Sarah M
- Katrina
- Oscar
- Cheryl
- Kylie
- Connie
- Caroline
- McKenzie
- Daniel
- Hannah
- Lark
- Raylie
- Alexis
- Rachel
- Blake
- Ray
- Eddy
- Jackie
- A.C.
- Abbie
- Carol
- Amy
- Tonu
- Hannah
- Anjil
- Teala
- Steve
- Kaitlin
- Amanda
- Rebekah
- Julie
- Stefanie
- Eva
- Sunnie
- Stephany
- Kristen

**Clarence & Alicia Hill, Charity, Harmony, Jonathan, Destiny**

**Jonathan & Lisa, Justus, Jerod, Jayden, Liberty, Jude, Laylah**

**Jake & Kourtney Hartsock, Harper, Braxton, Kooper, Sutton, Preslee**

**Chris & Megan Doke, Emma, Sophie, Alice, Bella, Isa**

**Chris & Julie, Beau, Nate, Brooks, Joy**

**Greg & Laura, fam**

**Bob & Randi**

**Patrick & Katie, Layla, Kayden, Baby**

**Brian & Allison, Halle, Ella, Haynes, Port**

**Gerod & fam,**

**Brian & Stacy, Kaelyn, Lauren, Joshua, Jason**

**Andrew & KK, Claire, Maddie, Jones**

**Donnie & Terri, Matthew, Jessica, Caleb; Astrid & Hubs**

**Nickolas & Adoyolle Eliis, Jeremiah, Jedidah, Josiah, Nehemiah, Nathan**

**Andrew & Jordyn, Will, Alice, Elliot, Baby**

**Zac & Sara, Henry, Margaret, Anna**

**Annamarie & Jordan, fam**

**Hein & Torree, Holly**

**Emily & Jason**

**Ben & Audrey**

**Stefan & Paige**

**Laura & Kenah, Nyala, Peter**

**Liz & Trey, Rosie, Miles**

**Blake & Lauren, fam**

**Tyler & Joi, fam**

**Josh & Becca, fam**

**Craig & Sharla Conway**

**Alex & Mikala, Reuben, Faye**

**John & Jillian, Samuel, Emma**

**Curtis & Rachel, Abigal, Ezra, Jesse**

**Jared & Bekah, Riah, Elias, Asher, Lena, Evey, Canaan, Hadassah**

**Robby & Sarah, fam**

**Ian**

**Erin**

**Josh**

**Jaime**

**Kim, Lori, Taylor**

**Larissa**

**Jessie**

**Carol**

**Aimee & James, Mia, Ruby, Elliott, Coraline, Lucy**

**Star-Lord**

**Zach**

**Mark & Mikala**

**Robin & Bobby**

**Elisheba**

> **1 Thessalonians 2:8 (NIV) We loved you so much that we were delighted to share with you not only the gospel of God but our lives as well, because you had become so dear to us.**

---

# All the churches in Norman

> **John 10:11-18 (CSB) “I am the good shepherd. The good shepherd lays down his life for the sheep. The hired hand, since he is not the shepherd and doesn’t own the sheep, leaves them and runs away when he sees a wolf coming. The wolf then snatches and scatters them. This happens because he is a hired hand and doesn’t care about the sheep.**

> **“I am the good shepherd. I know my own, and my own know me, just as the Father knows me, and I know the Father. I lay down my life for the sheep. But I have other sheep that are not from this sheep pen; I must bring them also, and they will listen to my voice. Then there will be one flock, one shepherd. This is why the Father loves me, because I lay down my life so that I may take it up again. No one takes it from me, but I lay it down on my own. I have the right to lay it down, and I have the right to take it up again. I have received this command from my Father.”**

- **Antioch OKC** 
- **Everlasting Life Baptist Church** - Terry & Carol Wilson 
- **FaithChurch** - Joshua and Tiffany Cossey
- **FaithChurch Hinton** - Mark and Brianna Lumpkin
- **LifeSpring Church** Jeff Robinett
- **Northgate Baptist** 
- **Calgary Church** - Daniel & Jamie Sweets, Lukas, Karis, Selah, & Zoe
- **Apostolic Worship Center** (**United Pentecostal**) - K. L. & Denise Borders
- **Holy Ancension Orthodox Church** - Fr. Jeremy
- **Victory Family** - Adam & Kristy Starling

---

## Timber Creek Church
- Josh & Abbey Mings, Owen & Ellie
- Glenn & Quirk, Lexi, Nixon, and Brody
- Amy & David Little, Ava & Holland

---

- **Fellowship Church** - Brad Hughes
- **Northeast Baptist Church** - Ed & Carol Sasnett
- **NorthHaven Church** - Jakob & Alyssa Topper, Hadley
- **FaithPointe Church** - Pastor Jim  & Ginger Gann
- **New Life Bible Church** - Jayson & Simi John, Moriah & Gideon
- **Cross Church of Norman** - Daniel & Jessica Kitchel, Abigail, Evie, Welles
- **St. Mark the Evangelist Catholic Church** - Fr. Timothy M. Fuller
- **Paradigm Church** - Ryan Wood
- **Memorial Presbyterian Church** - Rev. Tracy Evans
- **Church on Fire** - Pastors David and Tamara McGrew
- **Summit Church** - Todd Theissen
- **West Wind UUC** - Minister Andy Jacobs
- **Truth Church** - Pastor Jimmy  and Sabrina Smith
- **First Presbyterian Church** - Rev. Michael East
- **Trinity Presbyterian Church** - Justin & Meredith Westmoreland, Knox, Owen, Grace, and Lily
- **St. John's Episcopal** - Rev. John Borrego
- **McFarlin UMC** - Rev. Dr. Rockford Johnson
- **First Baptist Norman** - Dr. Wade Smith
- **First Christian Church** - David Spain
- **Community Missionary Baptist Church** - Richard Gaines
- **Trinity Lutheran Church** - Pastor David Nehrenz & Vicar Rob Schrader
- **Norman Seventh Day Adventist Church** - Harvey Gil
- **Alameda Baptist Church** - Tristan & Gayla Martin, kids
- **St. Joseph Catholic Churc** - Father Joseph Irwin 
- **Southern Oklahoma Chinese Baptist Church** - David & Linda Chan
- **Robinson Street Baptist Church** - Ivan & Tammy Moore
- **Immanuel Baptist Church** - Ken & Letha Huddleston

---

## Providence Road Church
- Blake Hilgenfeld
- Ben Schill
- Matt Mosier
- Jeremy Hager
- Bryce Buchanan
- Vicky Bumgarner
- Jay Frymire
- Nicole Hager
- Steve Morrow
- Kaylee Smith

---

- **Trinity Baptist Church** - Ronnie W. Rogers
- **Goodrich Memorial United Methodist Church** - Desi & Jason Brumit
- **Concord Missionary Baptist Church** - R.L. Clark
- **River Church** - David & Nancy Edwards
- **Seeker Church** - Russ & Janna Martin
- **Impact Church Norman** - Eddie and Leigh Thompson
- **Wildwood Church** - Mark & Kimberly, Joshua
- **Church of the Nazarene** - Brent & Amy, Cameron, Dawson
- **Grace Evangelical Lutheran Church** - John & Robin Vieths, kids
- **Go Church** - Pastor Chad & Helen Bartlett
- **Southern Canadian Valley Church of Christ**
- **St. Michael's Episcopal Church** - Rev. Dr. Jason Haddox & Rev. Laura Blazek
- **Westside Church of Christ**
  * Greg Giltner
  * Philip Johnson
  * Jeff Jennings
  * Ken Snethen
  * Tracey Talley

---

## Redeemer Church
- Andy & Christy McDonald, Jachin, Kimberlyn, Bo, Berline, and Caleb
- Andy McDonald
- Paul Kingery
- Jacob Labhan
- Stephen Branch
- Jon Dobbs
- Hayden Lane
- Paige Stroud
- Josh Caudill
- Craig Jackson
- Lindsey Oakes
- Allison Crampton
- Grace Depp

---

- **the church in Norman** - (Watchman Nee)
- **Alameda Church of Christ** - Rusty & Mitzi Tugman, Hope & Cooper
- **St. Thomas More** - Rev. James A Goins
- **Christian Center Church** - Pastors Derek and Diane Heldreth
- **Christ the King Presbyterian Church** - Mike & Janna Biggs
- **CrossPointe Church** - Mike & Debbie Butler
- **Norman Korean Baptist Church** - Senior Pastor Yeon-Seung Yang
- **Bethel Baptist** - Matt Brown, wife & fam
- **St. Anselm of Canterbury** - Blake Woods
- **University Lutheran Church** - Revd. Joseph E. Summerville, III, Donna, Brendan
- **Grace Fellowship Norman** - Rick & Andrea Anthony
- **The Wesley** - Joshua & Bonny Coats, Eli, Adelyn

---

# Frontline Norman

> **Matthew 9:35-38 (CSB) Jesus continued going around to all the towns and villages, teaching in their synagogues, preaching the good news of the kingdom, and healing every disease and every sickness. When he saw the crowds, he felt compassion for them, because they were distressed and dejected, like sheep without a shepherd. Then he said to his disciples, “The harvest is abundant, but the workers are few. Therefore, pray to the Lord of the harvest to send out workers into his harvest.”**

- Eric & Sarah, Amethyst, Aidan, Darby, Liam
- William Armer
- Andrew Aston
- Andie Aston
- Sarah Blake - niece Sophia recovering from spine surgery; Emily & Brian
- Daniel Bond
- Jamie Bond
- **Jessy Brock**
- Kimberly Burns - SINGLE; Surgery! Job interview! Another job outside Oklahoma!
- Jeff Cooke
- Annika Edgington - Getting settled in Delaware; Training in Texas - John
- Lauren Finocchiaro
- Charles Finocchirao
- Aaron Gayle
- Natasha Gayle
- Matt Haugland
- Sam Haugland
- **Ethan Inge**
- **Arden Nerius**
- **Nathan Sims**
- Gary Matthews
- Lisa Matthews
- Brittany Mayes - SINGLE
- Jordan Mayfield - SINGLE; Dad, Randy, health.
- Ashton Poyndexter - SINGLE; Christ in her glorified and exalted; To India; RUN THE RACE FAST AND HARD!
- Caleb Reichert
- Riley Roberson
- Emily Roberson
- Trey Scott 
- Kathleen Scott 
- Taylor Smith - SINGLE
- Phong Ta 
- Micah Thomason
- Melissa Thomason
- Destiny Warrior

Lord, every second of every day I must ask you: what is mine to do. I confess and repent that I don't turn to you. Lord, be gracious to me.

My God, give me your Spirit. Give me the fullness of the Spirit that raised Jesus Christ from the dead. Moreso than for me to preach your word but to turn my heart and cleanse my heart and make me just like you. 

Draw me closer. Let the world die to me so I can live to you.

---

## South Norman

Lord, please multiply

---

## Central Norman

Lord, please multiply

---

## 12th & Alameda

Hunter & Maddie

Bailey

Abby & Forrest

Isabella

Beth

Rachel

Claire

Hannah

Emily

---

## Brookhaven

Ethan & Arden

Jordan Campbell

---

## Rock Creek

Aaron & Natasha, Audrey

David & Letha, girls

Chuck & Lauren, Emily, Timothy, Rebecca, Zachary, Samuel

Scott & Melody, Emily, Adelyn, Caleb

Riley & Emily, Oliver

Andrew & Andie

Phong

Jessy & Carrie

Eric

Trey & Kathleen

Daniel & Jamie, Atlas, August

---

# Discipleship Group

Lord,

There is an full assault on your sons and daughters. Satan and his demons and the world is waging against us and it is all out.

God, you shall protect us because you are our shield.

But Lord, just like the mighty men of David, we are here to fight our sin and choke it with our bare hands until it dies.

We need your salvation. You have to cover us with your righteousness. Give us the call the strap our feet with the gospel of your peace. We need the gift of faith. We need your word.

Magnify and glorify Christ in us. 

Shatter the gates of hell.

I love you so much.

## Chuck & Lauren, Timothy, Emily, Rebekah, Zachary, Samuel
- Healing for Timothy
- Zachary - salvation; acting out - lying & stealing screentime, respectful, struggling with Lauren as teaching
- Samuel - salvation

## Riley & Emily, Oliver
- Oliver is here!
- Logan - salvation

## Scott & Melody, Emily, Adelyn, Caleb
- Emily
- Started school with students from everywhere
- Melody's mom & grandma - protection from exposure
- Wayne & Nicole Barber
- brother, Eric (Portland) vs parents who are Christian watches Fox News
- **Randy** - liver cancer

## Andrew & Andie
- Faith: pain; but success on surgery. Take away her pain. Heal her sweet head.
- Andie: visiting therapist, it's going well! Anxiety!
- Kale, brother
- friend, Collier & Rachel
- friend, Ben (Rachel's twin brother) & wife
- **mom Lara - heart attack**

---

# City of Norman

- Mayor Breea Clark
- Councilperson Elizabeth Foreman

I pray against attacks on our leaders. Shield their eyes and hearts.

But Father, if they do not know you, please turn their hearts towards you.

Lord bless my city and her people. 

> **1 Chronicles 29:18 O LORD, the God of Abraham, Isaac, and Israel, our fathers, keep forever such purposes and thoughts in the hearts of your people, and direct their hearts toward you.**

> **Acts 17:32 - 18:11 (CSB) When they heard about the resurrection of the dead, some began to ridicule him, but others said, “We’d like to hear from you again about this.” So Paul left their presence. However, some people joined him and believed, including Dionysius the Areopagite, a woman named Damaris, and others with them.**

> **After this, he left Athens and went to Corinth, where he found a Jew named Aquila, a native of Pontus, who had recently come from Italy with his wife Priscilla because Claudius had ordered all the Jews to leave Rome. Paul came to them, and since they were of the same occupation, tentmakers by trade, he stayed with them and worked. He reasoned in the synagogue every Sabbath and tried to persuade both Jews and Greeks.**

> **When Silas and Timothy arrived from Macedonia, Paul devoted himself to preaching the word and testified to the Jews that Jesus is the Messiah. When they resisted and blasphemed, he shook out his clothes and told them, “Your blood is on your own heads! I am innocent. From now on I will go to the Gentiles.” So he left there and went to the house of a man named Titius Justus, a worshiper of God, whose house was next door to the synagogue. Crispus, the leader of the synagogue, believed in the Lord, along with his whole household. Many of the Corinthians, when they heard, believed and were baptized.**

> **The Lord said to Paul in a night vision, “Don’t be afraid, but keep on speaking and don’t be silent. For I am with you, and no one will lay a hand on you to hurt you, because I have many people in this city.” He stayed there a year and a half, teaching the word of God among them.**

EOF
   cat << EOF > "$dir_prayers"/"$date_prayers"-"$base_pm_prayers".md
---
title: 'Evening Prayers for $day_prayers'
author: Joseph Louthan
type: post
publishDate: $date_prayers$pm_time
url: /$base_pm_prayers/$date_prayers-$base_pm_prayers/
categories:
 - Prayers
tags:
 - 'Prayers'
draft: true
---



---

# Pray to preach the gospel

> **2 Timothy 4:1-5 (ESV) I charge you in the presence of God and of Christ Jesus, who is to judge the living and the dead, and by his appearing and his kingdom: preach the word; be ready in season and out of season; reprove, rebuke, and exhort, with complete patience and teaching. For the time is coming when people will not endure sound teaching, but having itching ears they will accumulate for themselves teachers to suit their own passions, and will turn away from listening to the truth and wander off into myths. As for you, always be sober-minded, endure suffering, do the work of an evangelist, fulfill your ministry.**

---

# Prayers for past churches

---

## Mosaic East

---

## Antioch Norman

Lord,

Deliver them. Protect them. Keep them.

Shield them from the attacks of the enemy.

You are their Pastor and Lord. Do not let your little ones go astray.

Keep your presence there.

Have you way in them.

---

## Bethesda Church

**Pastor Dan & Becky Smith**

**Mary Evans**

**Stephen & Alisa Evans, fam**

**Anthony & wife, fam**

---

## Gateway Church

**Kristi**

**Camille**

**Court & Lauryn, kids**

---

## Catch the Fire DFW

**Alan Smith**

**Nancy & Sean Love, Lauren, Anna, Teddy**

**Lenore** 

**Jeremiah Duckett**

**Erica & Chris, Natalie, Ethan, Suzanna, Emerie**

**Shannon & Jessica, Eddie**

**Keri & Greg Solomon, Hazel, Penelope, Rowan**

**Michael & Erin, Brielle, Malachi, Sebastian**

**Jon & Lauren Pignatelli,**

**Kim Marin**

**Matthew Palant**

**Brad Braddy**

**Margie Spence**

**Tom Gardner**

---

## Antioch OKC

---

## Prayer for other churches

**Bruce Parnell, Stillwater RPC, Stillwater, OK**

**Dana Coverstone, Living Word Ministries AoG, Burkesville, KY**

**Terry Bennett, Messengers of Shiloh AoG, Vanleer, TN**

---

# Frontline

## Leaders within Frontline

Lord, would you raise up even more leaders for Norman. No matter what direction we take please tap more leaders.  More musicians. More of your Son in each of us so it won’t be dependent on any of us but on you alone.  

Lord, be glorified in our homes and in our city. Today. 

# Core

**Emily Brown**

**Aussie Enzbrenner**

# Bois

**Caleb Dyer**

**Colson Woodard**

**William Armer**

# Interns

- Caitlyn Swanson
- Mikayla Sander
- Stephanie White
- Paige Gariepy

- Katie Kalkulak
- AnnaMarie Ross
- Delaney Hammonds

- Savannah Chappell
- Abbigail Thomsen
- Emily Brown
- Jasmine Ingram

- JemiJean Jones
- Julianna Horner
- Mack McCullah

- Curtis Mitchell
- Zach Shomaker
- Aussie Enzbrenner

# Intern Staff

Ariel Mackey

Laker Greenwood

Zach Shomaker

Hope Wilson

Janelle Rogers

---

# Frontline Norman

Lord,

I believe I have your vision. I do not desire a ministry. My only desire is to faithfully handle your precious word and preach the gospel of Christ and him crucified.

But not my will but your will be done.

Amen.

---

# Frontline South

**Dena & Dave**
- Patrick
- Heather & hubs
- Ashlyn, Kadence, Liam, Coleman, Brayden, Gray, Madalyn, Hudson

**Sean & Jacqueline** 

**Andrew & Hilary, Evie, Eleanor, Bear** 

**Aaron & Kara, Beatrix & Peter**

**Brandon & Rachael, Claire & Jack**

**Tyler & Heather, Shepherd**

**Reuben** 

**Tyler & Melanie, Addy, Jocelyn, Kerslyn** 

**Will & Carli, Will, Theo**

**Dawn & Mark**
- Timothy, Elijah & Emily
- Tiffany & Nicky, Madilynn, Hunter, Hailey
- Daniel
- Sara & Rejoe, Emeril, Eredin, Elliot

**Deanna & James, Quinn**

**Eric & Megan, Leeland, Baby**

---

### Jhigh girls
* Becca Finocchiaro - identity in Jesus apart from siblings, confidence in who Jesus made her.
* Catherine Adams - just lost her step mom in a car wreck, has a lot of brokeness. salvation
* Tatum Coleman - Identity in Jesus and overall growth in Jesus. 
* Claire Laib - salvation

### Jhigh guys
* Ephraim Fox - salvation 
* Zachary Ebaucher - salvation 
* Noah Morgan - salvation
* Isaac Post - salvation 
* Coleman Evans - salvation 
* Seth Freeman - attends infrequently, salvation and understanding of who God is to become real.

### 9th grade guys 
* Liam Evans - for God to show himself to be real and tangible. 
* Bryson White - salvation. 
* JD Morgan - salvation 
* Julian Ebaucher - salvation 

### 11th and 12th Guys
* Timothy Finocchiaro - depression and friendships, feels very lonely and aimless.
* Hunter Loughlin - sexual addiction with pornography and struggles to know what the future holds, God to give him a bigger vision of his life and grow him in the Gospel.
* Charlie Longenbough - For Jesus to seem real and attractive to follow in the sake of the worlds offerings. Has an idea of Jesus with no real desire to follow him. 

### HS Girls
* Breeli Stanberry - Depth in the Gospel, is chameleon like and changes depending on who she is around.
* Brooklyn Stanberry - emotional health, struggles with friendships a lot, healing for a past friendship and relationship that fell thru
* Calea Moser - split between two parents, attends once a month
* Mallory Feighner - struggles deeply with what others think, gives her panic attacks, identity in Jesus and growth in emotional health and friendships with other girls
* Emily Finocchiaro - struggles with her loving and respecting mom and brother. really needs help forgiving ways her mom has fallen short and self awareness to see her own sin. praying also for her leadership capabilities to be released through maturing in Jesus 
* Sara Freeman - that God would show her life is more than sports. very talented athlete that has a heart for God but parents that prioritize sports. depth in the gospel. 
* Ashlyn Evans - for God to heal wounds and heartache from past friendships, give vision and direction for post HS in the next year. 
* Zoe Johnson - praying for her to show up more often, is often cliquey and struggles to allow herself to be known, praying God would convict her and give her a spiritual family if she came more.
* Shelby Mathews - emotional health and freedom from anxiety/depression, pressure from parents and sisters to be “perfect” 
* Hannah Lavender - raised by grandma, attends once a month, really needs healing with rough family and for the Lord to keep her from trying to find identity in hs guys and dating.

---

# Frontline Central

**Josh & Nancy, +kiddos**

---

# Frontline Shawnee

Pastor Ben - Lord, show me how I can be praying, encouraging and lifting up Ben and all the peoples at Shawnee.

---

# Frontline Yukon

---

# Frontline Edmond

---

# Frontline Downtown

---

# Frontline Midwest City

---

EOF
done
