#! /bin/bash
# date command: MACOS

userdir=$HOME
current_dir=$userdir/bin/
content_dir=$userdir/Sites/theologic.us/content/posts
dir_prayers=$content_dir/prayers
#base_prayers=evening_prayers
base_am_prayers=daily_prayers

# loop: print out 1-30
for ((i=0;i<=31;i++)); 
do 
   date_prayers=`date -j -v+"$i"d +%F`
   day_prayers=`date -j -v+"$i"d +'%A, %-e %B %Y'`
   am_time=T08:00:00-06:00
   #pm_time=T14:00:00-06:00
   cat << EOF > "$dir_prayers"/x-"$date_prayers"-"$base_am_prayers".md
---
title: 'Daily Prayers for $day_prayers'
author: Joseph Louthan
type: post
publishDate: $date_prayers$am_time
url: /$base_am_prayers/$date_prayers-$base_am_prayers/
categories:
  - Prayers
tags:
  - 'Prayers'
draft: true
---
## Give thanks to the Lord, for He is good and His steadfast love endures forever



**Sarah, my love** 

**Lord, help me to gentle, patient, and tender like you** 

**Lord, let me preach your gospel, die, and then be forgotten** 

**Lord, I cared not where or how I lived, or what hardships I went through, so I could but gain souls to Christ. —Henry Martyn** 

**For my Jonathan** 



## Next steps

*Minister at Frontline*

*Internship at Frontline*

*Management at Red Hat*

*Student at OU*



## For those who do not know You

**Yusef and Nichole** 

**Elijah & Ivy, Amber & Kara, Griffen, Gabe, Emma, Lacey, Grace, Lucy** 

**Natalie, Jackson, Kingston** 

**Reed & Sandy** 

**Johnny & Jamie, Kolton, Korbin** 

**Jeanny** 

**Jodi & Ryan, Piper, Rylee** 

**Jennifer & John; Brandon; Phillip & Keri; Pedigo & Deb** 

**Melissa & Micah, Noah, Levi, Judah** 

**James** 

**Jason, Molly** 

**Jansen & Mandy** 

**Sean & Sunny** 

**Evan** 

**Coleman & Wendy, Olivia, Bella, Ian**

**Mark & Nicole, Gabrielle** 

**Mark & Robin** 

**Louis** 

**Greg & wife** 

**Liz** 

**Eileen & Hubs, fam** 

**Ray** 

**Randall** 

**Cynthia** 

**Joe P** 

**George** 

**Wayne Barber** 

**Eric Robinson** 

**Jonathan & Jenn Williams** 

**Evan & Kaylee, Everett, Baby**



### Friends

**Andrew & Jordyn, Will, Alice, Elliot** 

**Alix & Braden** 

**Dena & Dave** 

*grandkids* **Ashlyn, Kadence, Liam, Coleman, Brayden, Gray, Madalyn, Hudson** 

**Reva & Ronnie** 

**Sean & Jacqueline** 

**Andrew & Hilary, Evie, Eleanor, Bear** 

**Tyler & Heather, Shepherd**

**Reuben** 

**Tyler & Melanie, Addy, Jocelyn, Kerslyn** 

**Will & Carli, kids**

**Dawn & Mark**

**Deanna & Hubs, Quinn**

**Holly & Jake, Jonah, Ellis, Finley**



## Discipleship Group

**Chuck & Lauren, Timothy, Emily, Rebekah, Zachary, Samuel** *(fear that comes with getting stuff done; Lauren's interview, job hunting; God's provision)* - 

**Riley & Emily** *(fear that comes with responsibility; baby boy: provision, joy, fear of God; provision of God, directed by God)* - 

**Scott & Melody, Emily, Adelyn, Caleb** *(Emily: sensitivities, nervousness, quietness, drawing to God; Wayne)* - 

**Andrew & Andie** *(all things marriage; peace, grace, joy; Faith's brain surgery 6/3/2020, Savannah's psych/personality disorder)* - 



## Family

**Sarah** 

**Yusef, Elijah, Ivy, Ava** 

**Marmie** *(Removal from Spiritual Isolation; Brought into Spiritual community; Equally yoked)* 



## Church

**Lord, what do you want your church to be? What have you seen your Bride to be? Align me with that!**

**God, who am I and what is my purpose?**

1. **Our relationship with the truth** - *Is there absolute truth or is there just my truth that I have to seek out?* - Where have I pieced together my own truth?

2. **Suspicion of all authority** - *Is all authority corrupted? Is the authority of Jesus corrupted?*

3. **Deconstruction of everything** - *Strip away everything and then cut the truth against my subjective prespective and experience*

4. **Expressive individualism** - *With or without boundaries and order? Freedom from or freedom to Christ?* 

5. **Consumerism** - *Going from citizens to individual; church as business; customer is always right* Pragmatism vs. Absolute Truth

6. **Instituational Corruption and Decline** -  *Cynical of all instituations: church, marriage, family, politics, education*

> **Ephesians 3:7–12 Of this gospel I was made a minister according to the gift of God’s grace, which was given me by the working of his power. To me, though I am the very least of all the saints, this grace was given, to preach to the Gentiles the unsearchable riches of Christ, and to bring to light for everyone what is the plan of the mystery hidden for ages in God, who created all things, so that through the church the manifold wisdom of God might now be made known to the rulers and authorities in the heavenly places. This was according to the eternal purpose that he has realized in Christ Jesus our Lord, in whom we have boldness and access with confidence through our faith in him.**

A. Church is the manifest wisdom of God that God continually preaches to angels.

B. Church is formed and continually sustained by the grace of God

C. Church is a community centered on Christ

**Frontline Norman**

**Antioch Norman** 

**Frontline South** 

**Frontline** 

**All the churches in Norman** 

**Norman** 

EOF
done