#! /bin/bash
# date command: MACOS

userdir=$HOME
current_dir=$userdir/bin/

# Set the prompt for the select command
PS3="Select a date or 'q' to quit: "

# Clear current weeks
week=$current_dir/7days
true > $week

# Give me the next five weeks starting on Sunday
next7days=( 1 2 3 4 5 6 7 )
for i in "${next7days[@]}"; do
  echo "$(date -j -v+"$i"d +%F)" >> 7days
done

followingdays=$(cat $week)

# Show a menu and ask for input.
select workingDay in $followingdays; do
    if [ -n "$workingDay" ]; then
        echo ${workingDay}
    fi
    break
done

# Working directories for posts
content_dir=$HOME/Sites/theologic.us/content/posts

# Working basenames for posts
category=memoir
Category=Memoir
filename='a-life-of-compromise'
tag='A Life of Compromise'

echo "Create a "$category" post for" $site" dated for "$workingDay"?"

read -p "Are you sure? " -n 1 -r
echo
if [[ $REPLY =~ ^[Yy]$ ]]
then
    cat << EOF > $content_dir/"$workingDay"-"$filename".md
---
title: 'A Life of Compromise: x. '
author: Joseph Louthan
type: post
publishDate: $date
url: /$category/$date-$filename_base/
categories:
  - $Category
tags:
  - '$tag'
draft: true
---
EOF

fi
