#! /bin/bash
# date command: MACOS

userdir=$HOME
current_dir=$userdir/bin/
#date=`date +%F -d "+$1 days"`
date=`date -v+1d +%F`
#day=`date +%A -d "+$1 days"`
day=`date -v+1d +%A`
currentdir=`basename "$PWD"`
site_dir=Sites
site='theologic.us'
content_dir=$HOME/$site_dir/$site/content/posts
category=memoir
Category=Memoir
filename='a-life-of-compromise'
tag='A Life of Compromise'

echo "Create a "$category" post for" $site" dated for tomorrow on" $day $date"?"

read -p "Are you sure? " -n 1 -r
echo
if [[ $REPLY =~ ^[Yy]$ ]]
then
    cat << EOF > $content_dir/"$date"-"$filename".md
---
title: 'A Life of Compromise, Ch x: '
author: Joseph Louthan
type: post
publishDate: $date
url: /$category/$date-$filename_base/
categories:
  - $Category
tags:
  - '$tag'
draft: true
---
EOF

fi
