#! /bin/bash
# date command: MACOS

userdir=$HOME
current_dir=$userdir/bin/

# Set the prompt for the select command
PS3="Select a date or 'q' to quit: "

# This coming Wedneday
wed=`date -j -v+wed +%F`

# Working directories for posts
content_dir=$HOME/Sites/theologic.us/content/posts

# Working basenames for posts
category=memoir
Category=Memoir
filename='a-life-of-compromise'
tag='A Life of Compromise'

echo "Create a "$category" post for" $site" dated for this coming Wednesday, "$wed"?"

read -p "Are you sure? " -n 1 -r
echo
if [[ $REPLY =~ ^[Yy]$ ]]
then
    cat << EOF > $content_dir/"$wed"-"$filename".md
---
title: 'A Life of Compromise: x. '
author: Joseph Louthan
type: post
publishDate: $wed
url: /$category/$wed-$filename_base/
categories:
  - $Category
tags:
  - '$tag'
draft: true
---
EOF

fi
