#! /bin/bash
# date command: MACOS

title='A Few Points for Friday '
subject='Few Points'
userdir=$HOME
bin_dir=$userdir/bin
subject_dir=few-points-friday
posts_dir=$userdir/Sites/theologic.us/content/posts/$subject_dir
weekof=$(date -j -v+fri '+%A %F')
Category='Links'
Tag='A Few Points for Friday'

# Working basenames for posts
# base_fri=commentary-romans
# base_tue=now-sings-my-soul-psalms
# base_wed=a-life-of-compromise
# base_tim=letters-to-timothy
# base_thu=family-devos-luke
base_fri=few-points-friday
# base_sat=sundry-saturday
# base_mark=commentary-mark

echo "Publishing 'A Few Points on Fridays' starting the week of" $weekof"!"

read -p "Are you sure? " -n 1 -r
echo
if [[ $REPLY =~ ^[Yy]$ ]]
then
	fris=( +0 +7 +14 +21 +28 +35 +42 +49 +56 +63 )
	for i in "${fris[@]}"; do
	  date_fris=`date -j -v+fri -v"$i"d +%F`
      cat << EOF > "$posts_dir"/"$date_fris"-"$base_fri".md
---
title: '$title'
author: Joseph Louthan
type: post
publishDate: $date_fris
url: /$base_fri/$date_fris-$base_fri/
categories:
  - $Category
tags:
  - '$Tag'
draft: true
---
EOF
	done
fi
