#! /bin/bash
# date command: MACOS

title='Thinking Through Ministry: 1 Timothy '
userdir=$HOME
bin_dir=$userdir/bin
subject_dir=3-letters-to-timothy
posts_dir=$userdir/Sites/theologic.us/content/posts/$subject_dir
weekof=$(date -j -v+wed '+%A %F')
Category='Ministry'
Tag='Philosophy of Ministry'

# Working basenames for posts
# base_mon=commentary-romans
# base_tue=now-sings-my-soul-psalms
# base_wed=a-life-of-compromise
# base_thu=family-devos-luke
# base_wed=few-points-wedday
base_tim=letters-to-timothy
# base_sat=sundry-saturday
# base_mark=commentary-mark

echo "Publishing 'Thinking Through Ministry' for the week of" $weekof"!"

read -p "Are you sure? " -n 1 -r
echo
if [[ $REPLY =~ ^[Yy]$ ]]
then
	weds=( +0 +7 +14 +21 +28 +35 +42 +49 +56 +63 )
	for i in "${weds[@]}"; do
	  date_weds=`date -j -v+wed -v"$i"d +%F`
      cat << EOF > "$posts_dir"/"$date_weds"-"$base_tim".md
---
title: '$title'
author: Joseph Louthan
type: post
publishDate: $date_weds
url: /$base_tim/$date_weds-$base_tim/
categories:
  - $Category
tags:
  - '$Tag'
draft: true
---
EOF
	done
fi
