#! /bin/bash
# date command: MACOS

title='Luke '
userdir=$HOME
bin_dir=$userdir/bin
subject_dir=4-family-devos-luke
posts_dir=$userdir/Sites/theologic.us/content/posts/$subject_dir
weekof=$(date -j -v+thu '+%A, %F')
Category='Devotions'
Tag='Family Devotions: Luke'

# Working basenames for posts
# base_mon=commentary-romans
# base_tue=now-sings-my-soul-psalms
# base_wed=a-life-of-compromise
base_thu=family-devos-luke
# base_fri=few-points-friday
# base_tim=letters-to-timothy
# base_sat=sundry-saturday
# base_mark=commentary-mark

echo "Publishing 'Devotions in Luke' for the week of" $weekof"!"

read -p "Are you sure? " -n 1 -r
echo
if [[ $REPLY =~ ^[Yy]$ ]]
then
	thus=( +0 +7 +14 +21 +28 +35 +42 +49 +56 +63 )
	for i in "${thus[@]}"; do
	  date_thus=`date -j -v+thu -v"$i"d +%F`
      cat << EOF > "$posts_dir"/"$date_thus"-"$base_thu".md
---
title: 'Luke 4:'
author: Joseph Louthan
type: post
publishDate: $date_thus
url: /$base_thu/x-$date_thus-$base_thu/
categories:
  - $Category
tags:
  - '$Tag'
draft: true
---
EOF
	done
fi
