#! /bin/bash
# date command: MACOS

subject=2-now-sings-my-soul-psalm
userdir=$HOME
bin_dir=$userdir/bin
posts_dir=$userdir/Sites/theologic.us/content/posts/$tag_dir
subject_dir=$posts_dir/$subject
weekof=$(date -j -v+tue +%F)
Category='Prayers'
Tag='Now Sings My Soul: Psalms'

# Working basenames for posts
# base_mon=commentary-romans
base_tue=now-sings-my-soul-psalms
# base_wed=a-life-of-compromise
# base_thu=family-devos-luke
# base_fri=few-points-friday
# base_tim=letters-to-timothy
# base_sat=sundry-saturday
# base_mark=commentary-mark

echo "Publishing for the week of" $weekof"!"

read -p "Are you sure? " -n 1 -r
echo
if [[ $REPLY =~ ^[Yy]$ ]]
then
	tues=( +0 +7 +14 +21 +28 +35 +42 +49 +56 +63 )
	for i in "${tues[@]}"; do
	  date_tues=`date -j -v+tue -v"$i"d +%F`
      cat << EOF > "$subject_dir"/x-"$date_tues"-"$base_tue".md
---
title: 'Now Sings My Soul: Psalm'
author: Joseph Louthan
type: post
publishDate: $date_tues
url: /$base_tue/x-$date_tues-$base_tue/
categories:
  - $Category
tags:
  - '$Tag'
draft: false
---
EOF
	done
fi
