#! /bin/bash
# date command: MACOS

title='Romans'
subject=Romans
userdir=$HOME
bin_dir=$userdir/bin
subject_dir=1-commentary-romans
posts_dir=$userdir/Sites/theologic.us/content/posts/$subject_dir
weekof=$(date -j -v+fri +%F)
Category='Commentary'
Tag='Commentary: Romans'

# Working basenames for posts
base_mon=commentary-romans
# base_tue=now-sings-my-soul-psalms
# base_wed=a-life-of-compromise
# base_thu=family-devos-luke
# base_fri=few-points-friday
# base_tim=letters-to-timothy
# base_sat=sundry-saturday
# base_mark=commentary-mark

echo "Publishing for the week of" $weekof"!"

read -p "Are you sure? " -n 1 -r
echo
if [[ $REPLY =~ ^[Yy]$ ]]
then
	mons=( +0 +7 +14 +21 +28 +35 +42 +49 +56 +63 )
	for i in "${mons[@]}"; do
	  date_mons=`date -j -v+mon -v"$i"d +%F`
      cat << EOF > "$posts_dir"/"$date_mons"-"$base_mon".md
---
title: '$title'
author: Joseph Louthan
type: post
publishDate: $date_mons
url: /$base_mon/x-$date_mons-$base_mon/
categories:
  - $Category
tags:
  - '$Tag'
draft: false
---
EOF
	done
fi
