#! /bin/bash
# date command: MACOS

title='Romans '
subject=Romans
userdir=$HOME
bin_dir=$userdir/bin
subject_dir=1-commentary-romans
posts_dir=$userdir/Sites/theologic.us/content/posts/$subject_dir
weekof=$workingSunday
Category='Commentary'
Tag='Commentary: Romans'

# Working basenames for posts
base_mon=commentary-romans

echo "Publishing Romans starting the week of" $weekof"!"

read -p "Are you sure? " -n 1 -r
echo
if [[ $REPLY =~ ^[Yy]$ ]]
then
	mons=( +0 +7 +14 +21 +28 +35 +42 +49 +56 +63 )
	for i in "${mons[@]}"; do
	  date_mons=`date -j -v+mon -v"$i"d +%F`
      cat << EOF > "$posts_dir"/"$date_mons"-"$base_mon".md
---
title: '$title'
author: Joseph Louthan
type: post
publishDate: $date_mons
url: /$base_mon/$date_mons-$base_mon/
categories:
  - $Category
tags:
  - '$Tag'
draft: true
---
EOF
	done
fi
