#! /bin/bash
# date command: MACOS

title='Sundry Saturdays: '
userdir=$HOME
bin_dir=$userdir/bin
subject_dir=sundry-saturday
posts_dir=$userdir/Sites/theologic.us/content/posts/$subject_dir
weekof=$(date -j -v+sat '+%A %F')
Category='Links'
Tag='Sundry Saturday'
base_sat=sundry-saturday

echo "Publishing 'Sundry Saturday' starting the week of" $weekof"!"

read -p "Are you sure? " -n 1 -r
echo
if [[ $REPLY =~ ^[Yy]$ ]]
then
	sats=( +0 +7 +14 +21 +28 +35 +42 +49 +56 +63 )
	for i in "${sats[@]}"; do
	  date_sats=`date -j -v+sat -v"$i"d +%F`
      cat << EOF > "$posts_dir"/"$date_sats"-"$base_sat".md
---
title: '$title'
author: Joseph Louthan
type: post
publishDate: $date_sats
url: /$base_sat/$date_sats-$base_sat/
categories:
  - $Category
tags:
  - '$Tag'
draft: true
---
EOF
	done
fi
