#! /bin/bash
# date command: MACOS

subject=5-letters-to-timothy
userdir=$HOME
bin_dir=$userdir/bin
posts_dir=$userdir/Sites/theologic.us/content/posts/$tag_dir
subject_dir=$posts_dir/$subject
weekof=$(date -j -v+fri +%F)
Category='Ministry'
Tag='Philosophy of Ministry'

# Working basenames for posts
# base_mon=commentary-romans
# base_tue=now-sings-my-soul-psalms
# base_wed=a-life-of-compromise
# base_thu=family-devos-luke
# base_fri=few-points-friday
base_tim=letters-to-timothy
# base_sat=sundry-saturday
# base_mark=commentary-mark

echo "Publishing for the week of" $weekof"!"

read -p "Are you sure? " -n 1 -r
echo
if [[ $REPLY =~ ^[Yy]$ ]]
then
	fris=( +0 +7 +14 +21 +28 +35 +42 +49 +56 +63 )
	for i in "${fris[@]}"; do
	  date_fris=`date -j -v+fri -v"$i"d +%F`
      cat << EOF > "$subject_dir"/x-"$date_fris"-"$base_tim".md
---
title: 'Thinking Through Ministry: 1 Timothy'
author: Joseph Louthan
type: post
publishDate: $date_fris
url: /$base_tim/x-$date_fris-$base_tim/
categories:
  - $Category
tags:
  - '$Tag'
draft: false
---
EOF
	done
fi
