#! /bin/bash

userdir=$HOME
current_dir=$userdir/bin/

# Clear current weeks
weeks=$current_dir/weeks
true > $weeks

# Set the prompt for the select command
PS3="Select a date or 'q' to quit: "

# Give me the next five weeks starting on Sunday
sundays=( 0 7 14 21 28 35 )
for i in "${sundays[@]}"; do
  echo "$(date -I -d "`dateround today sunday` +$i days")" >> "$weeks"
done

next5weeks=$(cat $weeks)

# Show a menu and ask for input.
select workingSunday in $next5weeks; do
    if [ -n "$workingSunday" ]; then
        echo ${workingSunday}
    fi
    break
done

# set your dates for each post
date_mon=`date -I -d "$workingSunday +1 days"`
date_tue=`date -I -d "$workingSunday +2 days"`
date_wed=`date -I -d "$workingSunday +3 days"`
date_thu=`date -I -d "$workingSunday +4 days"`
date_fri=`date -I -d "$workingSunday +5 days"`

# Working directories for posts
content_dir=/home/jlouthan/Sites/theologic.us/content/posts

# Working basenames for posts
base_testimony=a-life-of-compromise


echo "Publishing for the week of" $workingSunday "!"

read -p "Are you sure? " -n 1 -r
echo
if [[ $REPLY =~ ^[Yy]$ ]]
then
    cat << EOF > "$content_dir"/x"$date_mon"-"$base_testimony".md
---
title: 'A Life of Compromise: Ch '
author: Joseph Louthan
type: post
publishDate: $date_mon
url: /$base_testimony/$date_mon-$base_testimony/
categories:
  - Testimony
tags:
  - 'Testimony: A Life of Compromise'
draft: false
---
EOF
    cat << EOF > "$content_dir"/x"$date_tue"-"$base_testimony".md
---
title: 'A Life of Compromise: Ch '
author: Joseph Louthan
type: post
publishDate: $date_tue
url: /$base_testimony/$date_tue-$base_testimony/
categories:
  - Testimony
tags:
  - 'Testimony: A Life of Compromise'
draft: false
---
EOF
    cat << EOF > "$content_dir"/x"$date_wed"-"$base_testimony".md
---
title: 'A Life of Compromise: Ch '
author: Joseph Louthan
type: post
publishDate: $date_wed
url: /$base_testimony/$date_wed-$base_testimony/
categories:
  - Testimony
tags:
  - 'Testimony: A Life of Compromise'
draft: false
---
EOF
    cat << EOF > "$content_dir"/x"$date_thu"-"$base_testimony".md
---
title: 'A Life of Compromise: Ch '
author: Joseph Louthan
type: post
publishDate: $date_thu
url: /$base_testimony/$date_thu-$base_testimony/
categories:
  - Testimony
tags:
  - 'Testimony: A Life of Compromise'
draft: false
---
EOF
    cat << EOF > "$content_dir"/x"$date_fri"-"$base_testimony".md
---
title: 'A Life of Compromise: Ch '
author: Joseph Louthan
type: post
publishDate: $date_fri
url: /$base_testimony/$date_fri-$base_testimony/
categories:
  - Testimony
tags:
  - 'Testimony: A Life of Compromise'
draft: false
---
EOF
fi
