#! /bin/bash

# Clear current weeks
weeks=/home/jlouthan/bin/weeks
true > $weeks

# Set the prompt for the select command
PS3="Select a date or 'q' to quit: "

# Give me the next five weeks starting on Sunday
sundays=( 0 7 14 21 28 )
for i in "${sundays[@]}"; do
  echo "$(date -I -d "`dateround today sunday` +$i days")" >> "$weeks"
done

next5weeks=$(cat $weeks)

# Show a menu and ask for input.
select workingSunday in $next5weeks; do
    if [ -n "$workingSunday" ]; then
        echo ${workingSunday}
    fi
    break
done

# set your dates for each post
date_romans=`date -I -d "$workingSunday +1 days"`
date_psalms=`date -I -d "$workingSunday +3 days"`
date_luke=`date -I -d "$workingSunday +5 days"`

# Working directories for posts
content_dir=/home/jlouthan/Sites/theologic.us/content/posts

# Working basenames for posts
base_romans=study-romans
base_psalms=now-sings-my-soul-psalms
base_luke=family-devos-luke

echo "Publishing for the week of" $workingSunday "!"

read -p "Are you sure? " -n 1 -r
echo
if [[ $REPLY =~ ^[Yy]$ ]]
then
    cat << EOF > "$content_dir"/"$date_romans"-"$base_romans".md
---
title: 'Romans '
author: Joseph Louthan
type: post
publishDate: $date_romans$post_time
url: /$base_romans/$date_romans-$base_romans/
categories:
  - Theology
tags:
  - 'Studies: Romans'
draft: false
---
EOF
    cat << EOF > "$content_dir"/"$date_psalms"-"$base_psalms".md
---
title: 'Now Sings My Soul: Psalm '
author: Joseph Louthan
type: post
publishDate: $date_psalms$post_time
url: /$base_psalms/$date_psalms-$base_psalms/
categories:
  - Prayers
tags:
  - 'Now Sings My Soul: Psalms'
draft: false
---
<pre>
<div style="font-variant: small-caps;"></div>

</pre>
EOF
    cat << EOF > "$content_dir"/"$date_luke"-"$base_luke".md
---
title: 'Luke '
author: Joseph Louthan
type: post
publishDate: $date_luke$post_time
url: /$base_luke/$date_luke-$base_luke/
categories:
  - Theology
tags:
  - 'Family Devotions: Luke'
draft: false
---
EOF

fi
