#! /bin/bash
# date command: MACOS

userdir=$HOME
current_dir=$userdir/bin/

# Set the prompt for the select command
PS3="Select a date or 'q' to quit: "

# Clear current weeks
weeks=$current_dir/weeks
true > $weeks

# Give me the next five weeks starting on Sunday
sundays=( 0 7 14 21 28 35 )
for i in "${sundays[@]}"; do
  echo "$(date -j -v+sun -v+"$i"d +%F)" >> weeks
done

next5weeks=$(cat $weeks)

# Show a menu and ask for input.
select workingSunday in $next5weeks; do
    if [ -n "$workingSunday" ]; then
        echo ${workingSunday}
    fi
    break
done

# set your dates for each post
date_mon=`date -j -f %Y-%m-%d -v+1d $workingSunday +%F`
date_tue=`date -j -f %Y-%m-%d -v+2d $workingSunday +%F`
date_wed=`date -j -f %Y-%m-%d -v+3d $workingSunday +%F`
date_thu=`date -j -f %Y-%m-%d -v+4d $workingSunday +%F`
date_fri=`date -j -f %Y-%m-%d -v+5d $workingSunday +%F`

# Working directories for posts
content_dir=$HOME/Sites/theologic.us/content/posts

# Working basenames for posts
category=memoir
Category=Memoir
filename='a-life-of-compromise'
tag='A Life of Compromise'

echo "Publishing for the week of" $workingSunday "!"

read -p "Are you sure? " -n 1 -r
echo
if [[ $REPLY =~ ^[Yy]$ ]]
then
    cat << EOF > "$content_dir"/"$date_mon"-"$filename".md
---
title: 'A Life of Compromise, Ch x: '
author: Joseph Louthan
type: post
publishDate: $date_mon
url: /$category/$date_mon-$filename/
categories:
  - $Category
tags:
  - '$tag'
draft: true
---
EOF
    cat << EOF > "$content_dir"/"$date_tue"-"$filename".md
---
title: 'A Life of Compromise, Ch x: '
author: Joseph Louthan
type: post
publishDate: $date_tue
url: /$category/$date_tue-$filename/
categories:
  - $Category
tags:
  - '$tag'
draft: true
---
EOF
    cat << EOF > "$content_dir"/"$date_wed"-"$filename".md
---
title: 'A Life of Compromise, Ch x: '
author: Joseph Louthan
type: post
publishDate: $date_wed
url: /$category/$date_wed-$filename/
categories:
  - $Category
tags:
  - '$tag'
draft: true
---
EOF
    cat << EOF > "$content_dir"/"$date_thu"-"$filename".md
---
title: 'A Life of Compromise, Ch x: '
author: Joseph Louthan
type: post
publishDate: $date_thu
url: /$category/$date_thu-$filename/
categories:
  - $Category
tags:
  - '$tag'
draft: true
---
EOF
    cat << EOF > "$content_dir"/"$date_fri"-"$filename".md
---
title: 'A Life of Compromise, Ch x: '
author: Joseph Louthan
type: post
publishDate: $date_fri
url: /$category/$date_fri-$filename/
categories:
  - $Category
tags:
  - '$tag'
draft: true
---
EOF
fi
