#! /bin/bash
# date command: MACOS

bin=$HOME/bin/
content=/Users/jlouthan/Sites/theologic.us/content/posts
output_file=$bin/theologicus_word_count_today
date=$(date -j +%F)
this_word_count=$(find $content -name '*.md' -mtime -1 -type f -exec awk 1 {} + | wc -w | awk '{ print $1 }')

echo "Today's word count:" $this_word_count
