#! /bin/bash
# date command: MACOS

bin=$HOME/bin/
content=$HOME/Sites/theologic.us/content/posts
previous_file=$bin/wc-theo-previous
previous_count=$(cat $previous_count | awk '{ print $1 }')
output_file=$bin/wc_theologicus
date=$(date -j +%F)
this_word_count=$(find $content -name '*.md' -type f -exec awk 1 {} + | wc -w | awk '{ print $1 }')
words_written=$(($this_word_count-$previous_count))

echo -e "$date \t$this_word_count \t$words_written" >> $output_file

echo $this_word_count > $previous_count

# find $content -name '*.md' -mtime +8 -type f -exec awk 1 {} + | wc -w | awk '{ print $1 }' ; find $content -name '*.md' -mtime +1 -type f -exec awk 1 {} + | wc -w | awk '{ print $1 }'