#! /bin/bash
# date command: MACOS

content_dir=$HOME/Sites/theologic.us/content/posts
title='Now Sings My Soul: '
url_subject='now-sings-my-soul-psalm'
bin_dir=$userdir/bin
subject_dir=2-now-sings-my-soul-psalm
posts_dir=$content_dir/$subject_dir
# posts_dir=$userdir/Temp/$subject_dir
Category='Prayers'
Tag='Now Sings My Soul: Psalms'
month=Dec
day=22
year=2020
first_day=0
last_day=30
# loop: print out 1-30
for ((i=$first_day;i<=$last_day;i++)); 
do 
  date_prayers=`date -j -v"$month"m -v"$day"d -v"$year"y -v+"$i"d +%F`
  day_prayers=`date -j -v"$month"m -v"$day"d -v"$year"y -v+"$i"d +'%A, %-e %B %Y'`
  am_time=T06:00:00-06:00
  noon_time=T12:00:00-06:00
  pm_time=T20:00:00-06:00
  cat << EOF > "$posts_dir"/"$date_prayers"-am-"$url_subject".md
---
title: '$title'
author: Joseph Louthan
type: post
publishDate: $date_prayers$am_time
url: /$url_subject/$date_prayers-am-$url_subject/
categories:
  - $Category
tags:
  - '$Tag'
draft: true
---
<pre>
<div style="font-variant: small-caps;">

</div>

</pre>
EOF
   cat << EOF > "$posts_dir"/"$date_prayers"-noon-"$url_subject".md
---
title: '$title'
author: Joseph Louthan
type: post
publishDate: $date_prayers$noon_time
url: /$url_subject/$date_prayers-noon-$url_subject/
categories:
  - $Category
tags:
  - '$Tag'
draft: true
---
<pre>
<div style="font-variant: small-caps;">

</div>

</pre>
EOF
   cat << EOF > "$posts_dir"/"$date_prayers"-pm-"$url_subject".md
---
title: '$title'
author: Joseph Louthan
type: post
publishDate: $date_prayers$pm_time
url: /$url_subject/$date_prayers-pm-$url_subject/
categories:
  - $Category
tags:
  - '$Tag'
draft: true
---
<pre>
<div style="font-variant: small-caps;">

</div>

</pre>
EOF
done
