#! /bin/bash
# date command: MACOS
dow='tue'
title='Now Sings My Soul: Psalm 3:'
subject='Prayers in the Psalms'
url_subject='now-sings-my-soul-psalm'
userdir=$HOME
bin_dir=$userdir/bin
subject_dir=2-now-sings-my-soul-psalm
posts_dir=$userdir/Sites/theologic.us/content/posts/$subject_dir
# posts_dir=$userdir/Temp/$subject_dir
Category='Prayers'
Tag='Now Sings My Soul: Psalms'

# Clear current weeks
weeks=$bin_dir/weeks
true > $weeks

echo "Last entry for $subject: "
echo "$(ls -1 $posts_dir | grep md | tail -n1)"

# Set the prompt for the select command
echo "Setting up posts for $subject"
PS3="Select a date or 'q' to quit: "

# Give me the next five weeks starting on Sunday
sundays=( +0 +7 +14 +21 +28 +35 +42 +49 +56 +63 +70 +77 +84 +91 +98 +105 +112 +119 +126 +133 +140 +147 +154 +161 +168 +175 +182 +189 +196 +203 +210 +217 +224 +231 +238 +245 +252 )
for i in "${sundays[@]}"; do
  echo "$(date -j -v+"$dow" -v"$i"d +%F)" >> $bin_dir/weeks
done

next5weeks=$(cat $weeks)

# Show a menu and ask for input.
select workingDay in $next5weeks; do
    if [ -n "$workingDay" ]; then
        echo ${workingDay}
    fi
    break
done

# set your dates for each post
date=`date -j -f %Y-%m-%d $workingDay +%F`
day=`date -j -f %Y-%m-%d $date '+%A %F'`

echo "Publishing '$subject' starting the week of" $day"!"

read -p "Are you sure? " -n 1 -r
echo
if [[ $REPLY =~ ^[Yy]$ ]]
then
	future=( +0 +7 +14 +21 +28 +35 +42 +49 +56 +63 +70 +77 +84 +91 +98 +105 +112 +119 +126 +133 +140 +147 +154 +161 +168 +175 +182 +189 +196 +203 +210 +217 +224 +231 +238 +245 +252 )
  am_time=T06:00:00-06:00
  noon_time=T12:00:00-06:00
  pm_time=T20:00:00-06:00
	for i in "${future[@]}"; do
	  dates=`date -j -f %Y-%m-%d -v"$i"d $date +%F`
      cat << EOF > "$posts_dir"/"$dates"-am-"$url_subject".md
---
title: '$title'
author: Joseph Louthan
type: post
publishDate: $dates$am_time
url: /$url_subject/$dates-am-$url_subject/
categories:
  - $Category
tags:
  - '$Tag'
draft: true
---
<pre>
<div style="font-variant: small-caps;">

</div>

</pre>
EOF
   cat << EOF > "$posts_dir"/"$dates"-noon-"$url_subject".md
---
title: '$title'
author: Joseph Louthan
type: post
publishDate: $dates$noon_time
url: /$url_subject/$dates-noon-$url_subject/
categories:
  - $Category
tags:
  - '$Tag'
draft: true
---
<pre>
<div style="font-variant: small-caps;">

</div>

</pre>
EOF
   cat << EOF > "$posts_dir"/"$dates"-pm-"$url_subject".md
---
title: '$title'
author: Joseph Louthan
type: post
publishDate: $dates$pm_time
url: /$url_subject/$dates-pm-$url_subject/
categories:
  - $Category
tags:
  - '$Tag'
draft: true
---
<pre>
<div style="font-variant: small-caps;">

</div>

</pre>
EOF
done
fi