#! /bin/bash
# date command: macOS

dow='mon'
subject='Romans '
url_subject='commentary-romans'
bin_dir=$HOME/bin
subject_dir=1-commentary-romans
content_dir=$HOME/Sites/theologic.us/content/posts
posts_dir=$content_dir/$subject_dir
Category='Commentary'
Tag='Commentary: Romans'

# Clear current weeks
weeks=$bin_dir/weeks
true > $weeks

echo "Last entry for $subject: "
echo "$(ls -1 $posts_dir | grep md | tail -n1)"

# Set the prompt for the select command
echo "Setting up posts for $subject: "
PS3="Select a date or 'q' to quit: "

# Give me the next five weeks starting on Sunday
sundays=( +0 +7 +14 +21 +28 +35 +42 +49 +56 +63 +70 )
for i in "${sundays[@]}"; do
  echo "$(date -j -v+"$dow" -v"$i"d +%F)" >> $bin_dir/weeks
done

next5weeks=$(cat $weeks)

# Show a menu and ask for input.
select workingDay in $next5weeks; do
    if [ -n "$workingDay" ]; then
        echo ${workingDay}
    fi
    break
done

# set your dates for each post
date=`date -j -f %Y-%m-%d $workingDay +%F`
day=`date -j -f %Y-%m-%d $date '+%A %F'`

echo "Publishing '$subject' starting the week of" $day"!"

read -p "Are you sure? " -n 1 -r
echo
if [[ $REPLY =~ ^[Yy]$ ]]
then
	future=( +0 +7 +14 +21 +28 +35 +42 +49 +56 +63 +70 )
	for i in "${future[@]}"; do
	  dates=`date -j -f %Y-%m-%d -v"$i"d $date +%F`
      cat << EOF > "$posts_dir"/"$dates"-"$url_subject".md
---
title: '$subject '
author: Joseph Louthan
type: post
publishDate: $dates
url: /$url_subject/$dates-$url_subject/
categories:
  - $Category
tags:
  - '$Tag'
draft: true
---
EOF
	done
fi