#!/bin/bash
#### date command: macOS

#### Post and date specific variables
dow="mon"
Tag="Romans"
tag="romans"
title="Study: $Tag "
subject="$Tag"
subject_dir=2022
url_cat="bible-study"
url_sub="study-$tag"
Category="Bible Study"
Series="Bible Study: $Tag"
time="T06:00:00-06:00"
css="prayers"

#### Common variables
bin_dir=$HOME/bin
posts_dir=$HOME/Sites/theologic.us/content/posts/$subject_dir
# posts_dir=$HOME/Temp/$subject_dir

# mkdir working directory if there is none
mkdir -p "$posts_dir"

# Clear current weeks
weeks=$bin_dir/weeks
true > $weeks

echo "Last entry for $subject: "
echo "$(ls -1 $posts_dir | grep md | grep $tag | tail -n1)"


lastdate=$(head $posts_dir/`ls -1 $posts_dir | grep md | grep $tag | tail -n1` | grep publishDate)
echo $lastdate

# Set the prompt for the select command
echo "Setting up posts for $title: "
PS3="Select a date or "q" to quit: "

# Give me the next x weeks starting on $dow
for i in {0..10}; do
  echo "$(date -j -v+"$dow" -v +"$i"w +%F)" >> $weeks
done

listofdates=$(cat $weeks)

# Show a menu and ask for input.
select selectdate in $listofdates; do
    if [ -n "$selectdate" ]; then
        echo ${selectdate}
    fi
    break
done

echo "Publishing "$title" starting the week of" $selectdate"!"

read -p "Are you sure? " -n 1 -r
echo
if [[ $REPLY =~ ^[Yy]$ ]]
then
  for j in {00..09}; do
    postdate=$(date -j -v +"$j"w -f "%Y-%m-%d" "$selectdate" +%F)
  cat << EOF > "$posts_dir"/XX0"$j"-"$url_sub".md
---
title: "$title"
author: Joseph Louthan
publishDate: $postdate$time
url: /$url_cat/$postdate-$url_sub/
categories:
  - $Category
tags:
  - "$Tag"
series:
  - "$Series"
tocopen: true
css: "$css"
draft: true
---
## The Introduction

<div style="page-break-after: always;"></div>

## The Text

## The Support

<div style="page-break-after: always;"></div>

\`\`\`text
Where do you see God in the text? What does the text say about God?
\`\`\`

## Our God

<div style="page-break-after: always;"></div>

## The Gospel

<div style="page-break-after: always;"></div>

## Our Responsibility

## The Discussion

\`\`\`text
1. 
\`\`\`

\`\`\`text
2. 
\`\`\`

\`\`\`text
3. 
\`\`\`

\`\`\`text
4. 
\`\`\`

## The Prayer

<div style='font-variant: small-caps;'>

</div>

\`\`\`text

\`\`\`

## The Media

Today's episode at [The Study](http://study.theologic.us/podcast/)

\[[Apple](https://podcasts.apple.com/us/podcast/the-study/id1557102127)\]\[[Spotify](https://open.spotify.com/show/0Xs5qsNvWePyRqcmtOTPkR)\]\[[YouTube](http://youtube.theologic.us)\]\[[Twitch](http://twitch.theologic.us)\]\[[Twitter](https://twitter.com/theologic_us)\]\[[Facebook](https://www.facebook.com/groups/462231051477464)\]\[[Afreeca](https://bj.afreecatv.com/theologicus)\]\[[Discord](http://discord.theologic.us)\]


EOF
  done
fi