#!/bin/bash
#### date command: macOS

#### Post and date specific variables
dow="tue"
Tag="Survey of the New Testament"
tag="surveynt"
title="$Tag"
url_cat="$tag"
Category="Survey NT"

time="T00:00:00-05:00"
css="prayers"

subject="$title"
subject_dir=survey-bible
year_dir=2023
url_sub="$url_cat-$tag"
Series="$Tag"

#### Common variables
bin_dir=$HOME/bin
posts_dir=$HOME/Sites/theologic.us/content/posts/$subject_dir
current_dir=$HOME/Sites/theologic.us/content/posts/$year_dir
# posts_dir=$HOME/Temp/$subject_dir

# mkdir working directory if there is none
mkdir -p "$posts_dir"

# Clear current weeks
weeks=$bin_dir/weeks
true > $weeks

echo "Last entry for $subject: "
echo "$(ls -1 $posts_dir | grep md | grep $tag | tail -n1)"

lastdate=$(head $posts_dir/`ls -1 $posts_dir | grep md | grep $tag | tail -n1` | grep publishDate)
echo $lastdate

# Set the prompt for the select command
echo "Setting up posts for $subject: "
PS3="Select a date or "q" to quit: "

# Give me the next x weeks starting on $dow
for i in {0..52}; do
  echo "$(date -j -v+"$dow" -v +"$i"w +%F)" >> $weeks
done

listofdates=$(cat $weeks)

# Show a menu and ask for input.
select selectdate in $listofdates; do
    if [ -n "$selectdate" ]; then
        echo ${selectdate}
    fi
    break
done

echo "Publishing "$subject" starting the week of" $selectdate"!"

read -p "Are you sure? " -n 1 -r
echo
if [[ $REPLY =~ ^[Yy]$ ]]
then
  for j in {01..27}; do
    postdate=$(date -j -v +"$j"w -f "%Y-%m-%d" "$selectdate" +%F)
  cat << EOF > "$current_dir"/"$tag""$j".md
---
title: "$title"
author: Joseph Louthan
publishDate: $postdate$time
categories:
  - $Category
tags:
  - "$Tag"
series:
  - "$Series"
tocopen: true
css: "$css"
draft: true
---
## The Intro

<div style="page-break-after: always;"></div>

## The Book

<div style="page-break-after: always;"></div>

## The Survey


## The Christ

## The Resources

<img src="/images/resources/bible-CSB-paperback.jpg" align="left" width="100" style="padding-right: 10px" />Christian Standard Bible  
Holmon Publishing. 2020.  
[Goodreads](https://www.goodreads.com/book/show/30746802-csb-outreach-bible)

<p style="clear:both;">

---

<img src="/images/resources/bible-ESV-study-bible.jpg" align="left" width="100" style="padding-right: 10px" />ESV Study Bible  
Crossway. 2016.  
[Goodreads](https://www.goodreads.com/book/show/5031805-esv-study-bible?ac=1&from_search=true&qid=BEzDEv7NUE&rank=1)

<p style="clear:both;">

---

<img src="/images/resources/commentary-calvin-set.png" align="left" width="200" style="padding-right: 10px" />Calvin's Commentaries.  
by John Calvin.  
Baker. 2009.  
[Olive Tree](https://www.olivetree.com/store/product.php?productid=17517)

<p style="clear:both;">

---

<img src="/images/resources/commentary-ivp-background-ot-walton.jpg" align="left" width="100" style="padding-right: 10px" />The IVP Bible Background Commentary: Old Testament  
by .  
. .  
[Goodreads]()

<p style="clear:both;">

---

<img src="/images/resources/commentary-ivp-background-nt-keener.jpg" align="left" width="100" style="padding-right: 10px" />The IVP Bible Background Commentary: New Testament  
by Craig S. Keener.  
IVP Academic. January 3, 2014.  
[Goodreads](https://www.goodreads.com/book/show/17861691-the-ivp-bible-background-commentary)

<p style="clear:both;">

---

EOF
  done
fi