#!/bin/bash
#### date command: macOS

#### Post and date specific variables
dow="tue"
Tag="Survey of the Old & New Testaments"
tag="survey"
title="$Tag"
url_cat="$tag"
Category="Survey"

time="T06:00:00-05:00"
css="prayers"

subject="$title"
subject_dir=survey-bible
year_dir=2022
url_sub="$url_cat-$tag"
Series="$Tag"

#### Common variables
bin_dir=$HOME/bin
posts_dir=$HOME/Sites/theologic.us/content/posts/$subject_dir
current_dir=$HOME/Sites/theologic.us/content/posts/$year_dir
# posts_dir=$HOME/Temp/$subject_dir

# mkdir working directory if there is none
mkdir -p "$posts_dir"

# Clear current weeks
weeks=$bin_dir/weeks
true > $weeks

echo "Last entry for $subject: "
echo "$(ls -1 $posts_dir | grep md | grep $tag | tail -n1)"

lastdate=$(head $posts_dir/`ls -1 $posts_dir | grep md | grep $tag | tail -n1` | grep publishDate)
echo $lastdate

# Set the prompt for the select command
echo "Setting up posts for $subject: "
PS3="Select a date or "q" to quit: "

# Give me the next x weeks starting on $dow
for i in {0..30}; do
  echo "$(date -j -v+"$dow" -v +"$i"w +%F)" >> $weeks
done

listofdates=$(cat $weeks)

# Show a menu and ask for input.
select selectdate in $listofdates; do
    if [ -n "$selectdate" ]; then
        echo ${selectdate}
    fi
    break
done

echo "Publishing "$subject" starting the week of" $selectdate"!"

read -p "Are you sure? " -n 1 -r
echo
if [[ $REPLY =~ ^[Yy]$ ]]
then
  for j in {00..09}; do
    postdate=$(date -j -v +"$j"w -f "%Y-%m-%d" "$selectdate" +%F)
  cat << EOF > "$current_dir"/"$tag"0"$j"-"$url_sub".md
---
title: "$title"
author: Joseph Louthan
publishDate: $postdate$time
categories:
  - $Category
tags:
  - "$Tag"
series:
  - "$Series"
tocopen: true
css: "$css"
draft: true
---
## The Intro

<div style="page-break-after: always;"></div>

## The Book

<div style="page-break-after: always;"></div>

## The Survey


## The Christ

## The Resources

[<img src="https://images-na.ssl-images-amazon.com/images/I/91DXb+atXsL.jpg" align="left" width="100" style="padding-right: 10px" />Christian Standard Bible](https://amzn.to/3FbGqbM).  
Holmon Publishing. 2020.  
&nbsp;

___

[<img src="https://images-na.ssl-images-amazon.com/images/I/41nNWgurO3L._SX394_BO1,204,203,200_.jpg" align="left" width="100" style="padding-right: 10px" />ESV Study Bible](https://amzn.to/3FbGs38).  
Crossway. 2016.

&nbsp;

___

[<img src="https://images-na.ssl-images-amazon.com/images/I/41mjq2lbVJL._SX330_BO1,204,203,200_.jpg" align="left" width="100" style="padding-right: 10px" />Calvin's Commentaries](https://www.olivetree.com/store/product.php?productid=17517).  
by John Calvin.  
Baker. 2009.

&nbsp;

___

[<img src="https://images-na.ssl-images-amazon.com/images/I/81a-Z-PCV0L.jpg" align="left" width="100" style="padding-right: 10px" />The IVP Bible Background Commentary: Old Testament](https://www.amazon.com/gp/product/0830824782/ref=ppx_yo_dt_b_search_asin_title?ie=UTF8&psc=1).  
by John H. Walton, Victor H. Matthews, Mark W. Chavalas.  
IVP Academic. November 8, 2000.

&nbsp;

___

[<img src="https://images-na.ssl-images-amazon.com/images/I/81a-Z-PCV0L.jpg" align="left" width="100" style="padding-right: 10px" />The IVP Bible Background Commentary: New Testament](https://www.amazon.com/gp/product/0830824782/ref=ppx_yo_dt_b_search_asin_title?ie=UTF8&psc=1).  
by Craig S. Keener.  
IVP Academic. January 3, 2014.

&nbsp;

___

EOF
  done
fi