#!/bin/bash
#### date command: macOS

#### Post and date specific variables
dow="wed"
Tag="1689"
tag="$Tag"
title="1689 Baptist Confession of Faith, Chapter "
chapter="6"
url_cat="confessions"
Category="Confessions"
css="prayers"

subject="$title$Tag"
subject_dir=confession-1689
year_dir=2023
Series="$Tag."

#### Common variables
bin_dir=$HOME/bin
posts_dir=$HOME/Sites/theologic.us/content/posts/$subject_dir
current_dir=$HOME/Sites/theologic.us/content/posts/$year_dir
# posts_dir=$HOME/Temp/$subject_dir

# mkdir working directory if there is none
mkdir -p "$posts_dir"

# Clear current weeks
weeks=$bin_dir/weeks
true > $weeks

echo "Last entry for $subject: "
echo "$(ls -1 $posts_dir | grep md | grep $tag | tail -n1)"

lastdate=$(head $posts_dir/`ls -1 $posts_dir | grep md | grep $tag | tail -n1` | grep publishDate)
echo $lastdate

# Set the prompt for the select command
echo "Setting up posts for $subject: "
PS3="Select a date or "q" to quit: "

# Give me the next x weeks starting on $dow
for i in {0..25}; do
  echo "$(date -j -v+"$dow" -v +"$i"w +%F)" >> $weeks
done

listofdates=$(cat $weeks)

# Show a menu and ask for input.
select selectdate in $listofdates; do
    if [ -n "$selectdate" ]; then
        echo ${selectdate}
    fi
    break
done

echo "Publishing "$subject" starting the week of" $selectdate"!"

read -p "Are you sure? " -n 1 -r
echo
if [[ $REPLY =~ ^[Yy]$ ]]
then
  for j in {01..09}; do
    postdate=$(date -j -v +"$j"w -f "%Y-%m-%d" "$selectdate" +%F)
  cat << EOF > "$current_dir"/"$tag"-"$chapter"-"$j"-.md
---
title: "$title"
author: Joseph Louthan
publishDate: $postdate
  - $Category
tags:
  - "$Tag"
series:
  - "$Series"
tocopen: true
css: "$css"
draft: false
---
## The Text

TODO:

## The Chapter

## The Confession

## The Resources

<img src="/images/resources/dnd-1689-site-logo.png" align="left" width="100" style="padding-right: 10px" />Site: [Doctrine & Devotion](http://www.doctrineanddevotion.com/)  
[The 1689 Baptist Confession of Faith](https://www.the1689confession.com/)  
with Scriptural References

<p style="clear:both;">

---

<img src="/images/resources/confession-1689-judacious-reader-renihan.png" align="left" width="100" style="padding-right: 10px" />To the Judicious and Impartial Reader: Baptist Symbolics Volume 2.  
by James Renihan.  
Founders Press. 2022.  
[Goodreads](https://www.goodreads.com/book/show/17867976-modern-exposition-of-the-1689-baptist-confession-of-faith)

<p style="clear:both;">

---

<img src="/images/resources/confession-1689-new-exposition-ventura.jpg" align="left" width="100" style="padding-right: 10px" />A New Exposition of the London Baptist Confession of Faith of 1689    
by Rob Ventura.  
Mentor. January 17, 2023.  
[Amazon](https://www.amazon.com/Exposition-London-Baptist-Confession-Faith/dp/1527108902/ref=asc_df_1527108902/?tag=hyprod-20&linkCode=df0&hvadid=598295323603&hvpos=&hvnetw=g&hvrand=3877532160906942020&hvpone=&hvptwo=&hvqmt=&hvdev=c&hvdvcmdl=&hvlocint=&hvlocphy=9014286&hvtargid=pla-1722666080628&psc=1)

<p style="clear:both;">

---

<img src="/images/resources/confession-wcf-truths-we-confess-sproul.jpg" align="left" width="100" style="padding-right: 10px" />Truths We Confess: A Systematic Exposition of the Westminster Confession of Faith.  
Sproul, R. C.    
Orlando: Reformation Trust, 2019.  
[Goodreads](https://www.goodreads.com/book/show/50024945-truths-we-confess?ac=1&from_search=true&qid=ssTkBgIFwE&rank=1)

<p style="clear:both;">

---

<img src="/images/resources/confession-1689-masters.jpg" align="left" width="100" style="padding-right: 10px" />The Baptist Confession of Faith 1689: Or the Second London Confession with Scripture Proofs  
by Peter Masters.  
Wakeman Trust. January 1, 1981.  
[Goodreads](https://www.goodreads.com/book/show/1723671.Baptist_Confession_of_Faith_1689?ac=1&from_search=true&qid=HfdndsOLE6&rank=1)

<p style="clear:both;">

---

<img src="/images/resources/confession-1689-modern-exposition-waldron.jpg" align="left" width="100" style="padding-right: 10px" />Modern Exposition of the 1689 Baptist Confession of Faith.  
by Samuel E. Waldron.  
Evangelical Press. 2013.  
[Goodreads](https://www.goodreads.com/book/show/17867976-modern-exposition-of-the-1689-baptist-confession-of-faith)

<p style="clear:both;">

---

<img src="/images/resources/confession-wcf-banner-of-truth.jpg" align="left" width="100" style="padding-right: 10px" />The Westminster Confession: The Confession of Faith, The Larger and Shorter Catechism.  
Westminster Assembly.  
The Directory for the Public Worship of God, with Associated Historical Documents. 2018.   
[Goodreads](https://www.goodreads.com/book/show/39905592-the-westminster-confession?ac=1&from_search=true&qid=oMfahlcldC&rank=1)

<p style="clear:both;">

---

<img src="/images/resources/book-creedal-imperative-trueman.jpg" align="left" width="100" style="padding-right: 10px" />The Creedal Imperative.  
Carl R. Trueman    
Crossway, 2012.  
[Goodreads](https://www.goodreads.com/book/show/14452976-the-creedal-imperative?ac=1&from_search=true&qid=GTaJVGWwOY&rank=1)

<p style="clear:both;">
EOF
  done
fi