#!/bin/bash
#### date command: macOS

#### Post and date specific variables
dow="thu"
Tag="Genesis"
tag="genesis"
title="Study: "
url_cat="study"
Category="Study"
time="T06:00:00-05:00"
css="prayers"

subject="$title$Tag"
subject_dir=study-genesis
year_dir=$(date -j +%Y)
url_sub="$url_cat-$tag"
Series="$Tag"

#### Common variables
bin_dir=$HOME/bin
posts_dir=$HOME/Sites/theologic.us/content/posts/$subject_dir
current_dir=$HOME/Sites/theologic.us/content/posts/$year_dir
# posts_dir=$HOME/Temp/$subject_dir

# mkdir working directory if there is none
mkdir -p "$posts_dir"

# Clear current weeks
weeks=$bin_dir/weeks
true > $weeks

echo "Last entry for $subject: "
echo "$(ls -1 $posts_dir | grep md | grep $tag | tail -n1)"

lastdate=$(head $posts_dir/`ls -1 $posts_dir | grep md | grep $tag | tail -n1` | grep publishDate)
echo $lastdate

# Set the prompt for the select command
echo "Setting up posts for $subject: "
PS3="Select a date or "q" to quit: "

# Give me the next x weeks starting on $dow
for i in {0..20}; do
  echo "$(date -j -v+"$dow" -v +"$i"w +%F)" >> $weeks
done

listofdates=$(cat $weeks)

# Show a menu and ask for input.
select selectdate in $listofdates; do
    if [ -n "$selectdate" ]; then
        echo ${selectdate}
    fi
    break
done

echo "Publishing "$subject" starting the week of" $selectdate"!"

read -p "Are you sure? " -n 1 -r
echo
if [[ $REPLY =~ ^[Yy]$ ]]
then
  for j in {00..19}; do
    postdate=$(date -j -v +"$j"w -f "%Y-%m-%d" "$selectdate" +%F)
  cat << EOF > "$current_dir"/"$url_sub""$j".md
---
title: "$title"
author: Joseph Louthan
publishDate: $postdate$time
categories:
  - Commentaries
  - Study
tags:
  - "$Tag"
series:
  - "Study: $Tag"
tocopen: true
css: "$css"
draft: true
---
## The Introduction

<div style="page-break-after: always;"></div>

## The Text

## The Support

<div style="page-break-after: always;"></div>

\`\`\`text
Where do you see God in the text? What does the text say about God?
\`\`\`

## Our God

<div style="page-break-after: always;"></div>

## The Gospel

<div style="page-break-after: always;"></div>

## Our Response

## The Resources

<p style="clear:both;">

[<img src="https://images-na.ssl-images-amazon.com/images/I/41mjq2lbVJL._SX330_BO1,204,203,200_.jpg" align="left" width="150" style="padding-right: 10px" />Calvin's Commentaries](https://www.olivetree.com/store/product.php?productid=17517).  
by John Calvin.  
Baker. 2009.

<p style="clear:both;">

[<img src="https://images-na.ssl-images-amazon.com/images/I/416Q2TDAMKL.jpg" align="left" width="150" style="padding-right: 10px" />Genesis](https://www.amazon.com/Genesis-James-Montgomery-Boice/dp/0801066492/ref=sr_1_5?crid=111YG16YMHH51&keywords=Boice+Genesis&qid=1662635493&sprefix=boice+genesi%2Caps%2C195&sr=8-5).  
by James Montgomery Boice.  
Baker Books. May 1, 2006.

<p style="clear:both;">

[<img src="https://images-na.ssl-images-amazon.com/images/I/812oqRorpML.jpg" align="left" width="150" style="padding-right: 10px" />Genesis: Beginning and Blessing (Preaching the Word)](https://www.amazon.com/Genesis-Redesign-Beginning-Blessing-Preaching/dp/1433535521/ref=sr_1_1?keywords=preaching+the+word+genesis&qid=1662634993&sr=8-1).  
by R. Kent Hughes.  
Crossway. November 30, 2012.

<p style="clear:both;">

[<img src="https://images-na.ssl-images-amazon.com/images/I/41tYhwJCxSL.jpg" align="left" width="150" style="padding-right: 10px" />Genesis (Word Biblical Commentary)](https://www.amazon.com/gp/product/0849902002/ref=x_gr_bb_amazon?ie=UTF8&tag=x_gr_bb_amazon-20&linkCode=as2&camp=1789&creative=9325&creativeASIN=0849902002&SubscriptionId=1MGPYB6YW3HWK55XCGG2).  
by Gordon J. Wenham.  
Thomas Nelson Inc. October 9, 1987.

<p style="clear:both;">

[<img src="https://images-na.ssl-images-amazon.com/images/I/71irrBohMyL.jpg" align="left" width="150" style="padding-right: 10px" />The Gospel in Genesis](https://www.amazon.com/Gospel-Genesis-Fig-Leaves-Faith/dp/1433501201/ref=sr_1_1?crid=3HUWOZWRYHXFT&keywords=the+gospel+in+genesis&qid=1662634400&sprefix=the+gospel+in+genesis%2Caps%2C219&sr=8-1).  
by Martyn Lloyd-Jones.  
Crossway. 2009.

<p style="clear:both;">

EOF
  done
fi