#!/bin/bash
#### date command: macOS

#### Post and date specific variables
dow="sat"
Tag="Matthew"
tag="matthew"
title="Home Devotions: "
url_cat="home-devos"
Category="Home Devotions"
css="prayers"

subject="$title$Tag"
subject_dir=2023
url_sub="$url_cat-$tag"
Series="$subject"

#### Common variables
bin_dir=$HOME/bin
posts_dir=$HOME/Sites/theologic.us/content/posts/$subject_dir
# posts_dir=$HOME/Temp/$subject_dir

# mkdir working directory if there is none
mkdir -p "$posts_dir"

# Clear current weeks
weeks=$bin_dir/weeks
true > $weeks

echo "Last entry for $subject: "
echo "$(ls -1 $posts_dir | grep md | grep $tag | tail -n1)"

lastdate=$(head $posts_dir/`ls -1 $posts_dir | grep md | grep $tag | tail -n1` | grep publishDate)
echo $lastdate

# Set the prompt for the select command
echo "Setting up posts for $title: "
PS3="Select a date or "q" to quit: "

# Give me the next x weeks starting on $dow
for i in {0..10}; do
  echo "$(date -j -v+"$dow" -v +"$i"w +%F)" >> $weeks
done

listofdates=$(cat $weeks)

# Show a menu and ask for input.
select selectdate in $listofdates; do
    if [ -n "$selectdate" ]; then
        echo ${selectdate}
    fi
    break
done

echo "Publishing "$subject" starting the week of" $selectdate"!"

read -p "Are you sure? " -n 1 -r
echo
if [[ $REPLY =~ ^[Yy]$ ]]
then
  for j in {00..09}; do
    postdate=$(date -j -v +"$j"w -f "%Y-%m-%d" "$selectdate" +%F)
    cat << EOF > "$posts_dir"/"$url_sub""$j".md
---
title: "$title"
author: Joseph Louthan
publishDate: $postdate
categories:
  - $Category
tags:
  - "$Tag"
series:
  - "$Series"
tocopen: true
css: "$css"
draft: true
---
## The Text



## The Devotion



## The Resources

<p style="clear:both;">

<img src="/images/resources/commentary-calvin-set.png" align="left" width="200" style="padding-right: 10px" />Calvin's Commentaries.  
by John Calvin.  
Baker. 2009.  
[Olive Tree](https://www.olivetree.com/store/product.php?productid=17517)

<p style="clear:both;">

---

<img src="/images/resources/commentary-sproul-matthew.jpg" align="left" width="100" style="padding-right: 10px" />Matthew: An Expositional Commentary(https://a.co/d/iPO4KvF).  
by R.C. Sproul.  
Ligonier Ministries. October 29, 2019.  
[Goodreads](https://www.goodreads.com/book/show/14453116-matthew?ac=1&from_search=true&qid=1gLpP1i9jq&rank=1)

<p style="clear:both;">

---

<img src="/images/resources/commentary-esv-expository-set.jpg" align="left" width="200" style="padding-right: 10px" />ESV Expository Commentary: Matthew–Luke (Volume 8)  
Dan Doriani (Author)  
Iain M. Duguid, James M. Hamilton Jr., & Jay Sklar (Editors)  
Crossway. September 7, 2021.  
[Goodreads](https://www.goodreads.com/book/show/50611048-esv-expository-commentary-volume-8?ac=1&from_search=true&qid=KXgplk0Joa&rank=1)

<p style="clear:both;">

---

<img src="/images/resources/commentary-nac-blomberg-matthew.jpg" align="left" width="100" style="padding-right: 10px" />Matthew: An Exegetical and Theological Exposition of Holy Scripture (Volume 22) (The New American Commentary)(https://a.co/d/4nRKV6G).  
by Craig L. Blomberg.  
Holman Reference. May 1992.

<p style="clear:both;">

---

EOF
  done
fi
