#!/bin/bash
#### date command: macOS

#### Post and date specific variables
dow="fri"
Tag="Daniel"
tag="daniel"
title="Gospel OT: "
url_cat="gospel-ot"
Category="Gospel"
Series="Gospel OT: Major Prophets"
time="T00:00:00-05:00"
css="prayers"

subject="$title$Tag"
subject_dir=2022
url_sub="$url_cat-$tag"

#### Common variables
bin_dir=$HOME/bin
posts_dir=$HOME/Sites/theologic.us/content/posts/$subject_dir
# posts_dir=$HOME/Temp/$subject_dir

# mkdir working directory if there is none
mkdir -p "$posts_dir"

# Clear current weeks
weeks=$bin_dir/weeks
true > $weeks

echo "Last entry for $subject: "
echo "$(ls -1 $posts_dir | grep md | grep $tag | tail -n1)"

lastdate=$(head $posts_dir/`ls -1 $posts_dir | grep md | grep $tag | tail -n1` | grep publishDate)
echo $lastdate

# Set the prompt for the select command
echo "Setting up posts for $title: "
PS3="Select a date or "q" to quit: "

# Give me the next x weeks starting on $dow
for i in {0..10}; do
  echo "$(date -j -v+"$dow" -v +"$i"w +%F)" >> $weeks
done

listofdates=$(cat $weeks)

# Show a menu and ask for input.
select selectdate in $listofdates; do
    if [ -n "$selectdate" ]; then
        echo ${selectdate}
    fi
    break
done

echo "Publishing "$subject" starting the week of" $selectdate"!"

read -p "Are you sure? " -n 1 -r
echo
if [[ $REPLY =~ ^[Yy]$ ]]
then
  for j in {00..09}; do
    postdate=$(date -j -v +"$j"w -f "%Y-%m-%d" "$selectdate" +%F)
    cat << EOF > "$posts_dir"/"$tag""$j"-"$url_sub".md
---
title: "$title"
author: Joseph Louthan
publishDate: $postdate$time
categories:
  - $Category
tags:
  - "$Tag"
series:
  - "$Series"
tocopen: true
css: "$css"
draft: true
---
## The Introduction

<div style="page-break-after: always;"></div>

## The Text

<div style="page-break-after: always;"></div>

## The Meditation


## The Gospel


## The Discussion

\`\`\`text
1. 
\`\`\`

\`\`\`text
2. 
\`\`\`

\`\`\`text
3. 
\`\`\`

\`\`\`text
4. 
\`\`\`

## The Prayer

<div style='font-variant: small-caps;'>

</div>

\`\`\`text

\`\`\`


## The Resources

[<img src="https://images-na.ssl-images-amazon.com/images/I/51FEocBP3YL._SY291_BO1,204,203,200_QL40_FMwebp_.jpg" align="left" width="100" style="padding-right: 10px" />The Preacher's Commentary - Vol. 21- Daniel](https://amzn.to/3t3AaAt).  
by Sinclair Ferguson.  
Thomas Nelson. 2002.  

&nbsp;
&nbsp;

---

[<img src="https://images-na.ssl-images-amazon.com/images/I/41e9y9NB-VL._SX330_BO1,204,203,200_.jpg" align="left" width="100" style="padding-right: 10px" />Daniel (Reformed Expository Commentary)](https://amzn.to/3t5W85L).  
by Iain M. Duguid.  
P & R Publishing. 2008.  

&nbsp;
&nbsp;

---

EOF
	done
fi
