#!/bin/bash
#### date command: macOS

#### Post and date specific variables
dow="sat"
Tag="Matthew"
tag="matthew"
title="Home Devotions: "
url_cat="home-devos"
Category="Home Devotions"
time="T06:00:00-05:00"
css="prayers"

subject="$title$Tag"
subject_dir=2022
url_sub="$url_cat-$tag"
Series="$subject"

#### Common variables
bin_dir=$HOME/bin
posts_dir=$HOME/Sites/theologic.us/content/posts/$subject_dir
# posts_dir=$HOME/Temp/$subject_dir

# mkdir working directory if there is none
mkdir -p "$posts_dir"

# Clear current weeks
weeks=$bin_dir/weeks
true > $weeks

echo "Last entry for $subject: "
echo "$(ls -1 $posts_dir | grep md | grep $tag | tail -n1)"

lastdate=$(head $posts_dir/`ls -1 $posts_dir | grep md | grep $tag | tail -n1` | grep publishDate)
echo $lastdate

# Set the prompt for the select command
echo "Setting up posts for $title: "
PS3="Select a date or "q" to quit: "

# Give me the next x weeks starting on $dow
for i in {0..10}; do
  echo "$(date -j -v+"$dow" -v +"$i"w +%F)" >> $weeks
done

listofdates=$(cat $weeks)

# Show a menu and ask for input.
select selectdate in $listofdates; do
    if [ -n "$selectdate" ]; then
        echo ${selectdate}
    fi
    break
done

echo "Publishing "$subject" starting the week of" $selectdate"!"

read -p "Are you sure? " -n 1 -r
echo
if [[ $REPLY =~ ^[Yy]$ ]]
then
  for j in {00..09}; do
    postdate=$(date -j -v +"$j"w -f "%Y-%m-%d" "$selectdate" +%F)
    cat << EOF > "$posts_dir"/"$url_sub""$j".md
---
title: "$title"
author: Joseph Louthan
publishDate: $postdate$time
categories:
  - $Category
tags:
  - "$Tag"
series:
  - "$Series"
tocopen: true
css: "$css"
draft: true
---
## The Text



## The Devotion



## The Resources

## It Goes Without Say

[<img src="/images/resources/bible-CSB-paperback.jpg" align="left" width="200" style="padding-right: 10px" />The Holy Bible](https://amzn.to/3FbGqbM)

Many times, many teachers, preachers, and small group leaders (myself included) will "cut straight to the chase" and engage the commentary instead of engaging the Word of God. Remember, the commentaries are not without error—they are the observations of the author.

Slow down, pray, read, chew and meditate.

Note: I use the [Christian Standard Bible](https://csbible.com) version on this blog by default. Other translations, such as the [ESV](https://www.crossway.org/bibles/) or the [NIV1984](https://bibleportal.com/version/NIV1984), will be noted as such.
&nbsp;  

___

<p style="clear:both;">

[<img src="/images/resources/bible-ESV-study-bible.jpg" align="left" width="200" style="padding-right: 10px" />ESV Study Bible](https://amzn.to/3FbGs38)
Crossway. 2016.

Incredible resource.

I have purchased this resource multiple times over for myself and friends. If you want one and can't afford one, hit me up.

[<img src="/images/resources/icon-bible-olive-tree.png" align="right" width="100" style="padding-right: 10px" />](https://www.olivetree.com) If I had to pick just one resource (hardcover vs. leather vs. paperback vs. digital), I use it way more in my [Olive Tree Study Bible](https://www.olivetree.com) than anything else.  

___

## Commentaries & Books

I don't have a personal insightful recommendation on the following. I just wanted to have a stack of resources that I can check by and draw from if I need to.

<p style="clear:both;">

[<img src="/images/resources/commentary-calvin-set.png" align="left" width="250" style="padding-right: 10px" />Calvin's Commentaries](https://www.olivetree.com/store/product.php?productid=17517).  
by John Calvin.  
Baker. 2009.

[<img src="/images/resources/icon-bible-olive-tree.png" align="right" width="100" style="padding-right: 10px" />](https://www.olivetree.com)I mention this because in my go-to mobile Bible Study App, [Olive Tree](https://www.olivetree.com), Calvin's Commentaries are my go-to Commentary text of choice when I need clarification on the go. You can get the entire digital set for your phone (and computer) for about ~~$40~~ **$19.99** from Olive Tree!

<p style="clear:both;">

[<img src="/images/resources/commentary-sproul-matthew.jpg" align="left" width="150" style="padding-right: 10px" />Matthew: An Expositional Commentary](https://a.co/d/iPO4KvF).  
by R.C. Sproul.  
Ligonier Ministries. October 29, 2019.

If Sproul wrote it, 9.9/10 I am going to read it, use it, quote it, and recommend it. This volume is no exception.

<p style="clear:both;">

[<img src="/images/resources/commentary-esv-expository-set.jpg" align="left" width="250" style="padding-right: 10px" />ESV Expository Commentary: Matthew–Luke (Volume, 8)](https://a.co/d/557ktz).  
by Dan Doriani (Author)  
Iain M. Duguid, James M. Hamilton Jr., & Jay Sklar (Editors)  
Crossway. September 7, 2021.

So, I got the first three volumes released back a few years ago. Now they are up to 11 volumes. Also, I just created a budget that allows me to purchase one commentary per paycheck. (Bivocational is the providence of God.)

The authors are top notch. This will be referenced for sure.

<p style="clear:both;">

[<img src="/images/resources/commentary-nac-blomberg-matthew.jpg" align="left" width="150" style="padding-right: 10px" />Matthew: An Exegetical and Theological Exposition of Holy Scripture (Volume 22) (The New American Commentary)](https://a.co/d/4nRKV6G).  
by Craig L. Blomberg.  
Holman Reference. May 1992.

I am familiar with Blomberg. And I do like this series. This will also be referenced.

<p style="clear:both;">

EOF
  done
fi
