#!/bin/bash
#### date command: macOS

#### Post and date specific variables
dow="sun"
Tag="Psalms"
tag="psalm"
title="Praying Through: "
url_cat="praying-through"
Category="Prayers"
time="T06:00:00-06:00"
css="prayers"

subject="$title$Tag"
subject_dir=praying-through-psalm
year_dir=$(date -j +%Y)
url_sub="$url_cat-$tag"
Series="$Tag"

#### Common variables
bin_dir=$HOME/bin
posts_dir=$HOME/Sites/theologic.us/content/posts/$subject_dir
current_dir=$HOME/Sites/theologic.us/content/posts/$year_dir
# posts_dir=$HOME/Temp/$subject_dir

# mkdir working directory if there is none
mkdir -p "$posts_dir"

# Clear current weeks
weeks=$bin_dir/weeks
true > $weeks

echo "Last entry for $subject: "
echo "$(ls -1 $current_dir | grep md | grep $tag | tail -n1)"

lastdate=$(head $current_dir/`ls -1 $current_dir | grep md | grep $tag | tail -n1` | grep publishDate)
echo $lastdate

# Set the prompt for the select command
echo "Setting up posts for $subject: "
PS3="Select a date or "q" to quit: "

# Give me the next x weeks starting on $dow
for i in {0..20}; do
  echo "$(date -j -v+"$dow" -v +"$i"w +%F)" >> $weeks
done

listofdates=$(cat $weeks)

# Show a menu and ask for input.
select selectdate in $listofdates; do
    if [ -n "$selectdate" ]; then
        echo ${selectdate}
    fi
    break
done

echo "Publishing "$subject" starting the week of" $selectdate"!"

read -p "Are you sure? " -n 1 -r
echo
if [[ $REPLY =~ ^[Yy]$ ]]
then
  for j in {00..19}; do
    postdate=$(date -j -v +"$j"w -f "%Y-%m-%d" "$selectdate" +%F)
  cat << EOF > "$current_dir"/"$url_sub"-"$j".md
---
title: "$title"
author: Joseph Louthan
publishDate: $postdate$time
categories:
  - $Category
tags:
  - "$Tag"
series:
  - "$Series"
showtoc: false
css: "prayers"
css: "$css"
---
## The Psalms



## The Prayer

<div style="font-variant: small-caps;">

</div>

\`\`\`text

\`\`\`

EOF
  done
fi
