#!/bin/bash
#### date command: macOS

#### Post and date specific variables
Tag="Mark"
tag="mark"
title="Home Devotions: "

subject_dir=2022
url_cat="home-devotions"
url_sub="home-devos-$book"
Category="Home Devotions"
Series="Home Devotions: $Tag"
time="T06:00:00-06:00"
css="prayers"

#### Common variables
bin_dir=$HOME/bin
posts_dir=$HOME/Sites/theologic.us/content/posts/$subject_dir
# posts_dir=$HOME/Temp/$subject_dir

# mkdir working directory if there is none
mkdir -p "$posts_dir"

# Clear current weeks
weeks=$bin_dir/weeks
true > $weeks

echo "Last entry for $title: "
echo "$(ls -1 $posts_dir | grep md | grep $tag | tail -n1)"

lastdate=$(head $posts_dir/`ls -1 $posts_dir | grep md | grep $tag | tail -n1` | grep publishDate)
echo $lastdate

# Set the prompt for the select command
echo "Setting up posts for $title: "
PS3="Select a date or "q" to quit: "

# Give me the next 30 days to choose from
for i in {0..30}; do
  echo "$(date -j -v +"$i"d +%F)" >> $weeks
done

listofdates=$(cat $weeks)

# Show a menu and ask for input.
select selectdate in $listofdates; do
    if [ -n "$selectdate" ]; then
        echo ${selectdate}
    fi
    break
done

echo "Publishing "$title" starting on "$selectdate"!"

read -p "Are you sure? " -n 1 -r
echo
if [[ $REPLY =~ ^[Yy]$ ]]
then
	for j in {00..14}; do
  postday=$(date -j -v +"$j"d -f "%Y-%m-%d" "$selectdate" +%F-%a)
  postdate=$(date -j -v +"$j"d -f "%Y-%m-%d" "$selectdate" +%F)
  day=$(date -j -v +"$j"d -f "%Y-%m-%d" "$selectdate" +%a)
  cat << EOF > "$posts_dir"/XXX"$j"-"$day"-"$url_sub".md
---
title: "$title"
author: Joseph Louthan
publishDate: $postdate$time
url: /$url_cat/$postday-$url_sub/
categories:
  - $Category
tags:
  - "$Tag"
series:
  - "$Series"
tocopen: true
css: "$css"
draft: true
---
## The Text



## The Devotion



## The Discussion

\`\`\`text
1. 
\`\`\`

\`\`\`text
2. 
\`\`\`

\`\`\`text
3. 
\`\`\`

\`\`\`text
4. 
\`\`\`

## The Prayer from the Psalms

>

<div style='font-variant: small-caps;'>

</div>

\`\`\`text

\`\`\`

## The Media

Today's episode at [The Study](http://study.theologic.us/podcast/)

\[[Apple](https://podcasts.apple.com/us/podcast/the-study/id1557102127)\]\[[Spotify](https://open.spotify.com/show/0Xs5qsNvWePyRqcmtOTPkR)\]\[[YouTube](http://youtube.theologic.us)\]\[[Twitch](http://twitch.theologic.us)\]\[[Twitter](https://twitter.com/theologic_us)\]\[[Facebook](https://www.facebook.com/groups/462231051477464)\]\[[Afreeca](https://bj.afreecatv.com/theologicus)\]\[[Discord](http://discord.theologic.us)\]
EOF
  done
fi

find $posts_dir -type f \( -name "*Sun*.md" -o -name "*Sat*.md" \) -exec rm -f {} \;
