#!/bin/bash
#### date command: macOS

#### Post and date specific variables
dow="tue"
Tag="2 Timothy"
title="Gospel Meditations: $Tag "
subject_dir=2-gospel-meditations-nt
url_cat="gospel-meditations"
url_sub="2-timothy"
Category="Meditations"
Series="Gospel Meditations: Pastorals"
time="T06:00:00-06:00"
css="prayers"

#### Common variables
bin_dir=$HOME/bin
posts_dir=$HOME/Sites/theologic.us/content/posts/$subject_dir
# posts_dir=$HOME/Temp/$subject_dir

# mkdir working directory if there is none
mkdir -p "$posts_dir"

# Clear current weeks
weeks=$bin_dir/weeks
true > $weeks

echo "Last entry for $subject: "
echo "$(ls -1 $posts_dir | grep md | tail -n1)"

# Set the prompt for the select command
echo "Setting up posts for $subject: "
PS3="Select a date or "q" to quit: "

# Give me the next x weeks starting on $dow
for i in {1..35}; do
  echo "$(date -j -v+"$dow" -v +"$i"w +%F)" >> $weeks
done

listofdates=$(cat $weeks)

# Show a menu and ask for input.
select selectdate in $listofdates; do
    if [ -n "$selectdate" ]; then
        echo ${selectdate}
    fi
    break
done

echo "Publishing "$subject" starting the week of" $selectdate"!"

read -p "Are you sure? " -n 1 -r
echo
if [[ $REPLY =~ ^[Yy]$ ]]
then
  for j in {0..8}; do
    postdate=$(date -j -v +"$j"w -f "%Y-%m-%d" "$selectdate" +%F)
    cat << EOF > "$posts_dir"/"$postdate"-"$url_sub".md
---
title: "$title"
author: Joseph Louthan
publishDate: $postdate$time
url: /$url_cat/$postdate-$url_sub/
categories:
  - $Category
tags:
  - "$Tag"
series:
  - "$Series"
tocopen: true
css: "$css"
draft: true
---
## The Introduction

<div style="page-break-after: always;"></div>

## The Text

<div style="page-break-after: always;"></div>

## The Meditation


## The Gospel


## The Discussion

\`\`\`text
1. 
\`\`\`

\`\`\`text
2. 
\`\`\`

\`\`\`text
3. 
\`\`\`

\`\`\`text
4. 
\`\`\`

## The Prayer

<div style='font-variant: small-caps;'>

</div>

\`\`\`text

\`\`\`

## The Media

Today's episode at [The Study](http://study.theologic.us/podcast/)

\[[Apple](https://podcasts.apple.com/us/podcast/the-study/id1557102127)\]\[[Spotify](https://open.spotify.com/show/0Xs5qsNvWePyRqcmtOTPkR)\]\[[YouTube](http://youtube.theologic.us)\]\[[Twitch](http://twitch.theologic.us)\]\[[Twitter](https://twitter.com/theologic_us)\]\[[Facebook](https://www.facebook.com/groups/462231051477464)\]\[[Afreeca](https://bj.afreecatv.com/theologicus)\]\[[Discord](http://discord.theologic.us)\]
EOF
	done
fi