#! /bin/bash

site=$HOME/bin

#echo "Checking for any un-x posts with true draft statuses..."
#grep -R --color=always "draft: true" $posts/* | grep -v x- | grep -v prayer
#printf "%s " "Press any key to continue"
#read ans

#echo "Checking for any x posts with false draft statuses..."
#grep -R --color=always "draft: false" $posts/* | grep x-
#printf "%s " "Press any key to continue"
#read ans

echo "======================"
echo "Checking master branch"
cd $site
git pull origin master

echo "========================="
echo "Proceeding with deploy..."
cd $site
read -p "Commit descript: " desc
git add . &&\
git add -u &&\
git commit -m "$desc" &&\
git push
