#!/bin/bash
#### date command: macOS

#### Post and date specific variables
title="Calvin's Institutes Ch 10:"
category1="Reading"
category2="Books"
tag="Reading Notes"
series="Reading: Calvin's Institutes"
css="prayers"

#### Common variables
bin_dir=$HOME/bin
year=(date -j +%Y)
posts_dir=$HOME/Sites/theologic.us/content/posts/$year
TODO:

# mkdir working directory if there is none
mkdir -p "$posts_dir"

# Clear current weeks
weeks=$bin_dir/weeks
true > $weeks

echo "Last entry for $subject: "
echo "$(ls -1 $posts_dir | grep md | grep $tag | tail -n1)"

lastdate=$(head $posts_dir/`ls -1 $posts_dir | grep md | grep $tag | tail -n1` | grep publishDate)
echo $lastdate

# Set the prompt for the select command
echo "Setting up posts for $subject: "
PS3="Select a date or "q" to quit: "

# Give me the next 60 days to choose from
for i in {0..60}; do
  echo "$(date -j -v +"$i"d +%F)" >> $weeks
done

listofdates=$(cat $weeks)

# Show a menu and ask for input.
select selectdate in $listofdates; do
    if [ -n "$selectdate" ]; then
        echo ${selectdate}
    fi
    break
done

echo "Publishing "$subject" starting on "$selectdate"!"

read -p "Are you sure? " -n 1 -r
echo
if [[ $REPLY =~ ^[Yy]$ ]]
then
	for j in {0..30}; do
  postdate=$(date -j -v +"$j"d -f "%Y-%m-%d" "$selectdate" +%F)
  cat << EOF > "$posts_dir"/"$url_sub""$j".md
---
title: "$title"
author: Joseph Louthan
publishDate: $postdate$time
categories:
  - $category
tags:
  - "$tag"
series:
  - "$Series"
tocopen: true
css: "$css"
draft: true
---
## The Text



## The Devotion



## The Discussion

\`\`\`text
1. 
\`\`\`

\`\`\`text
2. 
\`\`\`

\`\`\`text
3. 
\`\`\`

\`\`\`text
4. 
\`\`\`

## The Prayer from the Psalms

>

<div style='font-variant: small-caps;'>

</div>

\`\`\`text

\`\`\`

<div style="page-break-after: always;"></div>

EOF
  done
fi
