#!/bin/bash
#### date command: macOS

#### Post and date specific variables
filename="calvin-institutes"
bookchapter="11"
Book="Book First: Of the Knowledge of God the Creator"
title="Calvin's Institutes"
category1="Reading"
category2="Books"
tag="Reading Notes"
series="Reading: Calvin's Institutes"
css="prayers"

#### Common variables
bin_dir=$HOME/bin
year=$(date -j +%Y)
site=$HOME/Sites/theologic.us
content=$site/content
posts=$content/posts
reading=$posts/reading
output=$posts/$year

# Clear current weeks
weeks=$bin_dir/weeks
true > $weeks

echo "Last entry for $title "
echo "$(ls -1 $reading | grep md | grep $filename | tail -n1)"

lastdate=$(head $reading/`ls -1 $reading | grep md | grep $filename | tail -n1` | grep publishDate)
echo $lastdate

# Set the prompt for the select command
echo "Setting up posts for $title: "
PS3="Select a date or "q" to quit: "

# Give me the next 60 days to choose from
for i in {00..30}; do
  echo "$(date -j -v +"$i"d +%F)" >> $weeks
done

listofdates=$(cat $weeks)

# Show a menu and ask for input.
select selectdate in $listofdates; do
    if [ -n "$selectdate" ]; then
        echo ${selectdate}
    fi
    break
done

echo "Publishing "$title" starting on "$selectdate"!"

read -p "Are you sure? " -n 1 -r
echo
if [[ $REPLY =~ ^[Yy]$ ]]
then
	for j in {0..9}; do
  postdate=$(date -j -v +"$j"d -f "%Y-%m-%d" "$selectdate" +%F)
  cat << EOF > "$output"/"$filename""$bookchapter""$j".md
---
title: "$title Ch $bookchapter$j: "
author: Joseph Louthan
publishDate: $postdate
categories:
  - $category1
  - $category2
tags:
  - "$tag"
series:
  - "$series"
tocopen: true
css: "$css"
draft: true
---

## The Title

Book: $Book

## The Sections

1.

## The Resources

<p style="clear:both;">

<img src="https://theologic.us/images/resources/book-calvin-beveridge-institutes.jpg" align="left" width="200" style="padding-right: 10px" />The Institutes of the Christian Religion.  
by John Calvin.  Translated by Henry Beveridge  
Hendrickson Publishers. January 1, 2008.  
[Goodreads](https://www.goodreads.com/book/show/1155340.Institutes_of_the_Christian_Religion)

<p style="clear:both;">

---

## The Copy

EOF
  done
fi
