#! /bin/bash
# date command: macOS

bin=$HOME/bin
wc=$bin/wc
sites=$HOME/Sites
theo_content=$sites/theologic.us/content/posts
prayer_content=$sites/prayers/
words_previous=$wc/words_previous
output_file=$wc/wc_theo_totals
date=$(date -j +%F)

read previous_count < $words_previous

theo_wc=$(find $theo_content -name '*.md' -type f -exec awk 1 {} + | wc -w | awk '{ print $1 }')
prayer_wc=$(find $prayer_content -type f -exec awk 1 {} + | wc -w | awk '{ print $1 }')
words_total=$(($theo_wc+$prayer_wc))
words_current=$(($words_total-$previous_count))
words_since=$(($words_total-177780))

echo -e "$date $theo_wc \t$prayer_wc \t$words_total \t$words_current $words_since\n" >> $output_file

echo "$words_total" > "$words_previous" 